Repository web-infra-dev/rspress, pull requests merged in 2024-07, with the labels that each got.

#1226 feat(deps)!: bump Rspack / Rsbuild 1.0.0-alpha.0
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/node/build.ts
  packages/core/src/node/initRsbuild.ts
  packages/plugin-preview/package.json
  packages/plugin-preview/src/index.ts
  packages/shared/package.json
  packages/theme-default/src/components/Nav/index.module.scss
  pnpm-lock.yaml
Labels: change: feat

#1230 docs: remove underlines between badges
  README.md
Labels: change: docs

#1231 fix: search panel race condition
  packages/theme-default/src/components/Search/SearchPanel.tsx
Labels: change: fix

#1233 perf(core): parallel the alias fetch
  packages/core/src/node/initRsbuild.ts
Labels: change: perf

#1240 feat: custom home footer
  e2e/fixtures/custom-home-footer/doc/index.mdx
  e2e/fixtures/custom-home-footer/package.json
  e2e/fixtures/custom-home-footer/rspress.config.ts
  e2e/fixtures/custom-home-footer/tsconfig.json
  e2e/tests/custom-home-footer.ts
  packages/document/docs/en/api/config/config-theme.mdx
  packages/document/docs/zh/api/config/config-theme.mdx
  packages/theme-default/src/components/HomeFooter/index.tsx
  pnpm-lock.yaml
Labels: change: feat

#1241 feat: improve menu item hover style and card background color
  packages/theme-default/src/components/HomeFeature/index.module.scss
  packages/theme-default/src/components/Sidebar/index.module.scss
  packages/theme-default/src/layout/HomeLayout/index.css
  packages/theme-default/src/styles/vars.css
Labels: change: feat

#1242 feat(deps): bump Rsbuild 1.0.0-alpha.6
  .changeset/chilly-flies-shout.md
  packages/cli/package.json
  packages/core/package.json
  packages/plugin-preview/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: feat

#1247 fix(theme-default): homepage hero link
  packages/document/docs/zh/index.md
  packages/theme-default/src/components/HomeHero/index.tsx
  packages/theme-default/src/layout/HomeLayout/index.tsx
Labels: change: fix

#1250 fix(deps): bump rsbuild 1.0.0-alpha.9
  .changeset/calm-numbers-do.md
  packages/cli/package.json
  packages/core/package.json
  packages/plugin-preview/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: fix

#1259 feat: add theme vars for customizing home page
  packages/document/theme/index.css
  packages/theme-default/src/components/HomeHero/index.module.scss
  packages/theme-default/src/layout/HomeLayout/index.css
Labels: change: feat

#1260 fix: should not render empty footer
  packages/theme-default/src/components/HomeFooter/index.tsx
Labels: change: fix

#1264 fix: replace < in render inline markdown
  packages/theme-default/src/logic/utils.ts
Labels: change: fix

#1265 fix(theme-default): features link in the homepage does not contain the base path
  packages/theme-default/src/components/HomeFeature/index.tsx
  packages/theme-default/src/components/HomeHero/index.tsx
  packages/theme-default/src/layout/HomeLayout/index.tsx
Labels: change: fix

#1271 docs: add example for Rsbuild configuration
  packages/document/docs/en/api/config/config-build.mdx
  packages/document/docs/en/plugin/system/plugin-api.mdx
  packages/document/docs/zh/api/config/config-build.mdx
  packages/document/docs/zh/plugin/system/plugin-api.mdx
Labels: change: docs

#1274 docs: add tool stack to homepage
  packages/document/i18n.json
  packages/document/package.json
  packages/document/theme/components/Benchmark/ProgressBar.tsx
  packages/document/theme/components/Benchmark/index.module.scss
  packages/document/theme/components/Benchmark/index.tsx
  packages/document/theme/components/ToolStack.module.scss
  packages/document/theme/components/ToolStack.tsx
  packages/document/theme/env.d.ts
  packages/document/theme/index.tsx
  packages/document/tsconfig.json
  pnpm-lock.yaml
Labels: change: docs

#1275 docs: improve useI18n examples
  packages/document/docs/en/api/_meta.json
  packages/document/docs/en/api/client-api/api-runtime.mdx
  packages/document/docs/en/fragments/useI18n.mdx
  packages/document/docs/en/guide/_meta.json
  packages/document/docs/en/guide/default-theme/i18n.mdx
  packages/document/docs/en/guide/start/introduction.mdx
  packages/document/docs/en/plugin/_meta.json
  packages/document/docs/en/plugin/system/introduction.mdx
  packages/document/docs/zh/api/_meta.json
  packages/document/docs/zh/api/client-api/api-runtime.mdx
  packages/document/docs/zh/fragments/useI18n.mdx
  packages/document/docs/zh/guide/_meta.json
  packages/document/docs/zh/guide/default-theme/i18n.mdx
  packages/document/docs/zh/guide/start/introduction.mdx
  packages/document/docs/zh/plugin/_meta.json
  packages/document/docs/zh/plugin/system/introduction.mdx
  packages/document/i18n.json
  packages/document/theme/components/ToolStack.tsx
Labels: change: docs

#1276 fix: correct GitHub spelling
  packages/create-rspress/template/docs/index.md
  packages/document/docs/en/guide/basic/deploy.mdx
  packages/document/docs/en/guide/basic/ssg.mdx
  packages/document/docs/en/guide/default-theme/navbar.mdx
  packages/document/docs/en/guide/start/introduction.mdx
  packages/document/docs/zh/guide/basic/deploy.mdx
  packages/document/docs/zh/guide/basic/ssg.mdx
  packages/document/docs/zh/guide/default-theme/navbar.mdx
  packages/document/docs/zh/guide/start/introduction.mdx
Labels: change: fix

#1281 fix(theme): adjust the dir sidebar font size
  .changeset/chilly-cycles-agree.md
  packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
Labels: change: fix

#1207 docs: add metadata and header tag info
  packages/document/docs/en/guide/basic/custom-page.mdx
Labels: change: docs

#1282 docs: translate custom tags guide
  packages/document/docs/en/guide/basic/custom-page.mdx
  packages/document/docs/zh/guide/basic/custom-page.mdx
Labels: change: docs

#1289 fix(theme-default): uiSwitch prop of Layout component not work
  e2e/fixtures/custom-layout-ui-switch/doc/index.mdx
  e2e/fixtures/custom-layout-ui-switch/package.json
  e2e/fixtures/custom-layout-ui-switch/rspress.config.ts
  e2e/fixtures/custom-layout-ui-switch/theme/index.tsx
  e2e/fixtures/custom-layout-ui-switch/tsconfig.json
  e2e/tests/custom-layout-ui-switch.test.ts
  packages/theme-default/src/layout/Layout/index.tsx
  pnpm-lock.yaml
Labels: change: fix

#1293 fix: catch can not found tailwindcss error when debug
  packages/theme-default/src/node/source-build-plugin.ts
Labels: change: fix
