Repository web-infra-dev/rspress, pull requests merged in 2024-06, with the labels that each got.

#1136 feat: increase title font size to distinguish from main text
  packages/theme-default/src/components/HomeHero/index.tsx
  packages/theme-default/src/layout/DocLayout/docComponents/title.tsx
  packages/theme-default/tailwind.config.ts
Labels: change: feat

#1153 feat(deps): bump Rsbuild v0.7.3
  e2e/fixtures/with-base/package.json
  package.json
  packages/cli/package.json
  packages/core/package.json
  packages/create-rspress/package.json
  packages/document/package.json
  packages/modern-plugin-rspress/package.json
  packages/plugin-api-docgen/package.json
  packages/plugin-auto-nav-sidebar/package.json
  packages/plugin-last-updated/package.json
  packages/plugin-medium-zoom/package.json
  packages/plugin-preview/package.json
  packages/plugin-rss/package.json
  packages/plugin-shiki/package.json
  packages/plugin-typedoc/package.json
  packages/shared/package.json
  packages/theme-default/package.json
  pnpm-lock.yaml
Labels: change: feat

#1157 fix(plugin-playground): export EditorProps error
  packages/plugin-playground/src/web/editor.tsx
  packages/plugin-playground/src/web/index.ts
Labels: change: fix

#1170 feat: support inject context when generate sidebar
  e2e/fixtures/auto-nav-sidebar/doc/api/_meta.json
  e2e/fixtures/auto-nav-sidebar/doc/api/config/_meta.json
  e2e/fixtures/auto-nav-sidebar/doc/api/config/config-frontmatter.mdx
  e2e/tests/auto-nav-sidebar.test.ts
  packages/document/docs/en/api/config/config-frontmatter.mdx
  packages/document/docs/en/guide/basic/auto-nav-sidebar.mdx
  packages/document/docs/zh/api/config/config-frontmatter.mdx
  packages/document/docs/zh/guide/basic/auto-nav-sidebar.mdx
  packages/plugin-auto-nav-sidebar/src/type.ts
  packages/plugin-auto-nav-sidebar/src/utils.ts
  packages/plugin-auto-nav-sidebar/src/walk.ts
  packages/shared/src/types/defaultTheme.ts
  packages/shared/src/types/index.ts
  packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
Labels: change: feat

#1173 docs: fix discord badge
  README.md
Labels: change: docs

#1168 feat: support extra head tags, extension to #1145
  e2e/fixtures/custom-headers/doc/index.mdx
  e2e/fixtures/custom-headers/doc/jane/index.mdx
  e2e/fixtures/custom-headers/package.json
  e2e/fixtures/custom-headers/rspress.config.ts
  e2e/fixtures/custom-headers/tsconfig.json
  e2e/tests/custom-headers.test.ts
  packages/core/src/node/build.ts
  packages/core/src/node/utils/renderHead.ts
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/en/api/config/config-frontmatter.mdx
  packages/shared/src/node-utils/loadFrontMatter.ts
  packages/shared/src/types/index.ts
  pnpm-lock.yaml
Labels: change: feat

#1175 docs: add head config doc in zh
  e2e/fixtures/custom-headers/package.json
  e2e/fixtures/custom-headers/rspress.config.ts
  e2e/tests/custom-headers.test.ts
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/document/docs/zh/api/config/config-frontmatter.mdx
  pnpm-lock.yaml
Labels: change: docs

#1181 fix(theme-default): scroll restoration
  packages/theme-default/src/logic/useUISwitch.ts
Labels: change: fix

#1179 feat: generate 404.html by default
  packages/core/src/node/build.ts
  packages/document/docs/404.mdx
  packages/theme-default/src/layout/Layout/index.tsx
Labels: change: feat

#1166 feat: support client redirect
  e2e/fixtures/client-redirects/doc/index.mdx
  e2e/fixtures/client-redirects/package.json
  e2e/fixtures/client-redirects/rspress.config.ts
  e2e/fixtures/client-redirects/tsconfig.json
  e2e/tests/client-redirects.test.ts
  packages/document/docs/en/plugin/official-plugins/_meta.json
  packages/document/docs/en/plugin/official-plugins/client-redirects.mdx
  packages/document/docs/en/plugin/official-plugins/overview.mdx
  packages/document/docs/zh/plugin/official-plugins/_meta.json
  packages/document/docs/zh/plugin/official-plugins/client-redirects.mdx
  packages/document/docs/zh/plugin/official-plugins/overview.mdx
  packages/plugin-client-redirects/LICENSE
  packages/plugin-client-redirects/README.md
  packages/plugin-client-redirects/modern.config.ts
  packages/plugin-client-redirects/package.json
  packages/plugin-client-redirects/src/components/Redirect.tsx
  packages/plugin-client-redirects/src/index.ts
  packages/plugin-client-redirects/src/modern-app-env.d.ts
  packages/plugin-client-redirects/src/types.ts
  packages/plugin-client-redirects/tests/tsconfig.json
  packages/plugin-client-redirects/tsconfig.json
  packages/plugin-client-redirects/vitest.config.ts
  pnpm-lock.yaml
Labels: change: feat

#1184 docs: remove usued documate config
  packages/document/documate.json
  packages/document/package.json
  packages/document/rspress.config.ts
Labels: change: docs

#1185 feat: format JSON in generated virtual modules
  packages/core/src/node/mdx/loader.ts
  packages/core/src/node/runtimeModule/i18n.ts
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/core/tests/__snapshots__/prismLanguages.test.ts.snap
Labels: change: feat

#1188 fix: code highlight in preview plugin
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/core/tests/__snapshots__/prismLanguages.test.ts.snap
  packages/core/tests/prismLanguages.test.ts
  packages/plugin-preview/src/index.ts
Labels: change: fix

#1194 fix(core): duplicate html title tags during ssg
  e2e/tests/custom-headers.test.ts
  packages/core/src/node/build.ts
Labels: change: fix

#1195 fix: only append base to internal non-relative urls
  packages/runtime/src/utils.ts
Labels: change: fix

#1212 feat: better gracefully shutdown
  packages/cli/src/index.ts
Labels: change: feat

#1213 style: enhance color of code token inserted/deleted
  packages/runtime/src/utils.ts
  packages/theme-default/src/layout/DocLayout/docComponents/prisim-theme.ts
  packages/theme-default/src/styles/base.css
Labels: change: feat

#1219 fix: generated head tag have a extra brace
  .changeset/tall-squids-watch.md
  e2e/fixtures/custom-headers/rspress.config.ts
  e2e/tests/custom-headers.test.ts
  packages/core/src/node/utils/renderHead.ts
Labels: change: fix

#1221 docs: fix OG tags examples
  packages/document/docs/en/api/config/config-frontmatter.mdx
  packages/document/docs/en/fragments/internal-components.mdx
  packages/document/docs/zh/api/config/config-frontmatter.mdx
  packages/document/docs/zh/fragments/internal-components.mdx
Labels: change: docs
