Repository web-infra-dev/rspress, pull requests merged in 2024-08, with the labels that each got.

#1295 feat(deps): bump Rsbuild 1.0.1-beta.9
  .changeset/famous-apes-drop.md
  packages/cli/package.json
  packages/core/package.json
  packages/plugin-preview/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: feat

#1296 fix(core): ignore globby publicDir route
  e2e/fixtures/public-dir/doc/index.mdx
  e2e/fixtures/public-dir/doc/public/rspress-icon.png
  e2e/fixtures/public-dir/doc/public/test.html
  e2e/fixtures/public-dir/doc/public/test.js
  e2e/fixtures/public-dir/doc/public/test.mdx
  e2e/fixtures/public-dir/package.json
  e2e/fixtures/public-dir/rspress.config.ts
  e2e/fixtures/public-dir/tsconfig.json
  e2e/tests/public-dir.test.ts
  packages/core/src/node/route/RouteService.ts
  pnpm-lock.yaml
Labels: change: fix

#1304 docs: add Rslib links
  README.md
Labels: change: docs

#1305 docs: bump `@rstack-dev/doc-ui` to add Rslib and awesome Rspack
  packages/document/package.json
  packages/document/theme/components/ToolStack.tsx
  packages/document/theme/index.tsx
  pnpm-lock.yaml
Labels: change: docs

#1312 fix(watch): improve watch solution, ignore _meta.json out of doc root dir
  .changeset/thick-moons-cry.md
  packages/cli/src/index.ts
Labels: change: fix

#1311 fix(core/sidebar): should not generate sidebar in homePage with "type": "dir" route
  e2e/fixtures/issue-1309/docs/_meta.json
  e2e/fixtures/issue-1309/docs/guide/_meta.json
  e2e/fixtures/issue-1309/docs/guide/index.md
  e2e/fixtures/issue-1309/docs/guide/test-dir/a.md
  e2e/fixtures/issue-1309/docs/guide/test-file.md
  e2e/fixtures/issue-1309/docs/index.md
  e2e/fixtures/issue-1309/package.json
  e2e/fixtures/issue-1309/rspress.config.ts
  e2e/fixtures/issue-1309/tsconfig.json
  e2e/tests/auto-nav-sidebar.test.ts
  e2e/tests/issue-1309.test.ts
  e2e/utils/getSideBar.ts
  packages/theme-default/src/logic/useSidebarData.ts
  pnpm-lock.yaml
Labels: change: fix

#1313 fix: should watch whole doc root dir for add/delete file
  .changeset/cyan-yaks-pull.md
  packages/cli/src/index.ts
Labels: change: fix

#1316 feat(theme): replace twitter with x in soicalLinks config
  packages/document/docs/en/api/config/config-theme.mdx
  packages/document/docs/en/guide/default-theme/navbar.mdx
  packages/document/docs/zh/api/config/config-theme.mdx
  packages/document/docs/zh/guide/default-theme/navbar.mdx
  packages/document/rspress.config.ts
  packages/shared/src/types/defaultTheme.ts
  packages/theme-default/src/components/SocialLinks/LinkContent.tsx
  packages/theme-default/src/components/SocialLinks/presetIcons.tsx
Labels: change: feat

#1325 feat: add new `ssg.strict` config
  e2e/fixtures/ssg-fail-strict/doc/Component.ts
  e2e/fixtures/ssg-fail-strict/doc/index.mdx
  e2e/fixtures/ssg-fail-strict/package.json
  e2e/fixtures/ssg-fail-strict/rspress.config.ts
  e2e/fixtures/ssg-fail-strict/tsconfig.json
  e2e/tests/ssg-fail-strict.test.ts
  packages/core/src/node/build.ts
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/shared/src/types/index.ts
  pnpm-lock.yaml
Labels: change: feat

#1329 fix: window unexpected href when feature link is not configured
  e2e/fixtures/page-type-home/doc/index.md
  e2e/tests/page-type-home.test.ts
  packages/theme-default/src/components/HomeFeature/index.tsx
Labels: change: fix

#1330 fix: should not redirect when page is visited by bot
  packages/theme-default/src/logic/useRedirect4FirstVisit.ts
Labels: change: fix

#1334 docs: enable strict SSG
  packages/document/rspress.config.ts
Labels: change: docs

#1343 fix: apply replaceRules in object frontmatter
  e2e/fixtures/replace-rules/doc/_meta.json
  e2e/fixtures/replace-rules/doc/content.mdx
  e2e/fixtures/replace-rules/doc/foo/content.mdx
  e2e/fixtures/replace-rules/doc/foo/index.mdx
  e2e/fixtures/replace-rules/doc/index.mdx
  e2e/fixtures/replace-rules/rspress.config.ts
  e2e/tests/replace-rules.test.ts
  packages/core/src/node/runtimeModule/siteData/extractPageData.ts
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
Labels: change: fix

#1347 fix: use `__webpack_public_path__` for search index url
  packages/core/src/node/initRsbuild.ts
  packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
  packages/theme-default/src/global.d.ts
Labels: change: fix

#1342 docs: link and example on using components
  packages/document/docs/en/guide/advanced/custom-theme.mdx
  packages/document/docs/en/guide/basic/use-mdx.mdx
  packages/document/docs/zh/guide/advanced/custom-theme.mdx
  packages/document/docs/zh/guide/basic/use-mdx.mdx
Labels: change: docs

#1348 feat: re-design container colors
  packages/document/docs/en/guide/basic/use-mdx.mdx
  packages/document/docs/zh/guide/basic/use-mdx.mdx
  packages/plugin-container-syntax/container.css
Labels: change: feat

#1358 fix: yarn create command in PackageManagerTabs
  e2e/fixtures/package-manager-tabs/doc/index.mdx
  e2e/fixtures/package-manager-tabs/package.json
  e2e/fixtures/package-manager-tabs/rspress.config.ts
  e2e/tests/package-manager-tabs.test.ts
  packages/theme-default/src/components/PackageManagerTabs/index.tsx
  pnpm-lock.yaml
Labels: change: fix

#1363 fix(style): improve work break for a tags
  packages/theme-default/src/components/Overview/index.module.scss
  packages/theme-default/src/layout/DocLayout/docComponents/index.module.scss
Labels: change: fix

#1367 docs: add SECURITY.md
  SECURITY.md
Labels: change: docs

#1366 fix(theme): fix highlight effect when operating with keyboard (#1364)
  packages/theme-default/src/components/Search/SearchPanel.tsx
  packages/theme-default/src/components/Search/SuggestItem.tsx
  packages/theme-default/src/components/Search/index.module.scss
Labels: change: fix

#1369 fix(plugin-auto-nav-sidebar): auto generated sidebar should consider `route.extensions` when `_meta.json` don't exists
  e2e/fixtures/auto-nav-sidebar-no-meta/doc/api/data.json
  e2e/fixtures/auto-nav-sidebar-no-meta/doc/api/rspress-config/1.png
  packages/plugin-auto-nav-sidebar/src/index.ts
  packages/plugin-auto-nav-sidebar/src/utils.ts
  packages/plugin-auto-nav-sidebar/src/walk.ts
Labels: change: fix
