Repository web-infra-dev/rspress, pull requests merged in 2024-11, with the labels that each got.

#1549 perf(cli): enable Node.js compile cache
  packages/cli/bin/rspress.js
Labels: change: perf

#1551 fix: incorrect code link color
  packages/theme-default/src/styles/code.css
Labels: change: fix

#1553 fix: remove lookbehind syntax to compatibile with Safari
  .changeset/khaki-chefs-deliver.md
  packages/theme-default/src/logic/utils.ts
Labels: change: fix

#1554 docs: modify Docusaurus related
  packages/document/docs/en/guide/start/introduction.mdx
  packages/document/docs/zh/guide/start/introduction.mdx
Labels: change: docs

#1557 fix: render inline markdown with generic syntax
  e2e/fixtures/inline-markdown/doc/index.mdx
  e2e/fixtures/inline-markdown/doc/inline/_meta.json
  e2e/fixtures/inline-markdown/doc/inline/all.mdx
  e2e/fixtures/inline-markdown/doc/inline/bold.mdx
  e2e/fixtures/inline-markdown/doc/inline/code.mdx
  e2e/fixtures/inline-markdown/doc/inline/emphasis.mdx
  e2e/fixtures/inline-markdown/doc/inline/escape.mdx
  e2e/fixtures/inline-markdown/doc/inline/index.mdx
  e2e/fixtures/inline-markdown/doc/inline/str.mdx
  e2e/fixtures/inline-markdown/package.json
  e2e/fixtures/inline-markdown/rspress.config.ts
  e2e/fixtures/inline-markdown/tsconfig.json
  e2e/tests/inline-markdown.test.ts
  packages/theme-default/package.json
  packages/theme-default/src/logic/utils.ts
  pnpm-lock.yaml
Labels: change: fix

#1562 feat: render delete syntax and generate correct header anchor for strong/em/del syntax
  .changeset/flat-spiders-complain.md
  e2e/fixtures/inline-markdown/doc/inline/_meta.json
  e2e/fixtures/inline-markdown/doc/inline/all.mdx
  e2e/fixtures/inline-markdown/doc/inline/delete.mdx
  e2e/tests/inline-markdown.test.ts
  packages/core/package.json
  packages/theme-default/src/logic/utils.ts
  pnpm-lock.yaml
Labels: change: feat

#1563 fix: aside text should break word
  packages/theme-default/src/components/Aside/index.scss
Labels: change: fix

#1572 feat(plugin-auto-nav-sidebar): support index as the dir click section and custom-link context
  .changeset/two-lizards-rule.md
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/_meta.json
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/guide/_meta.json
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/guide/index-in-meta/_meta.json
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/guide/index-in-meta/index.md
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/guide/index-md-convention/_meta.json
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/guide/index-md-convention/index.md
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/guide/index-mdx-convention/_meta.json
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/guide/index-mdx-convention/index.mdx
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/guide/index.md
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/guide/same-name.mdx
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/guide/same-name/_meta.json
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/guide/single-md/index.md
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/guide/single-mdx/index.mdx
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/index.md
  e2e/fixtures/auto-nav-sidebar-dir-convention/package.json
  e2e/fixtures/auto-nav-sidebar-dir-convention/rspress.config.ts
  e2e/fixtures/auto-nav-sidebar-dir-convention/tsconfig.json
  e2e/fixtures/auto-nav-sidebar/doc/api/_meta.json
  e2e/fixtures/auto-nav-sidebar/doc/api/link/_meta.json
  e2e/tests/auto-nav-sidebar-dir-convension.test.ts
  e2e/tests/auto-nav-sidebar.test.ts
  packages/document/docs/en/guide/basic/auto-nav-sidebar.mdx
  packages/document/docs/zh/guide/basic/auto-nav-sidebar.mdx
  packages/plugin-auto-nav-sidebar/src/utils.ts
  packages/plugin-auto-nav-sidebar/src/walk.ts
  packages/runtime/src/utils.ts
  packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
  packages/theme-default/src/components/Sidebar/SidebarItem.tsx
  packages/theme-default/src/components/Sidebar/index.tsx
  pnpm-lock.yaml
Labels: change: feat

#1573 fix(plugin-api-docgen): Avoid style pollution
  packages/plugin-api-docgen/static/global-components/API.scss
  packages/plugin-api-docgen/static/global-components/API.tsx
Labels: change: fix

#1578 fix(sidebar): /api/index.html /api/index /api should show same sidebar
  e2e/tests/auto-nav-sidebar-dir-convension.test.ts
  packages/theme-default/src/components/Sidebar/index.tsx
  packages/theme-default/src/index.ts
  packages/theme-default/src/logic/useSidebarData.ts
  packages/theme-default/src/logic/utils.ts
Labels: change: fix

#1580 fix(deps): remove unused @loadable/component
  packages/core/package.json
  pnpm-lock.yaml
Labels: change: fix

#1581 docs: ts-node is no longer required
  packages/cli/package.json
  packages/document/docs/en/guide/start/getting-started.mdx
  packages/document/docs/zh/guide/start/getting-started.mdx
  packages/document/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: docs

#1583 fix(deps): clean up more unused dependencies
  packages/core/package.json
  packages/plugin-preview/package.json
  packages/theme-default/package.json
  pnpm-lock.yaml
Labels: change: fix

#1590 fix: remove `@modern-js/utils` dependency
  .changeset/new-students-promise.md
  packages/core/package.json
  packages/modern-plugin-rspress/package.json
  packages/modern-plugin-rspress/src/lanchDoc.ts
  packages/modern-plugin-rspress/src/utils.ts
  packages/plugin-api-docgen/package.json
  packages/plugin-api-docgen/src/docgen.ts
  packages/plugin-api-docgen/src/index.ts
  pnpm-lock.yaml
Labels: change: fix

#1591 perf: remove `react-transition-group` dependency
  e2e/fixtures/custom-plugin/package.json
  e2e/fixtures/plugin-preview/package.json
  packages/theme-default/package.json
  packages/theme-default/src/components/LocalSideBar/index.scss
  packages/theme-default/src/components/LocalSideBar/index.tsx
  pnpm-lock.yaml
Labels: change: perf

#1600 fix: remove htmlparser2 and use reg to check valid html elements
  e2e/fixtures/inline-markdown/doc/index.mdx
  e2e/tests/inline-markdown.test.ts
  packages/theme-default/package.json
  packages/theme-default/src/logic/utils.ts
  pnpm-lock.yaml
Labels: change: fix

#1602 fix: some remark packages should be devDependencies
  packages/core/package.json
  pnpm-lock.yaml
Labels: change: fix

#1605 fix: should generate unique aside link id when using different syntax
  .changeset/cold-bulldogs-kiss.md
  e2e/fixtures/custom-id/doc/guide.mdx
  e2e/fixtures/toc-id/doc/index.mdx
  e2e/fixtures/toc-id/package.json
  e2e/fixtures/toc-id/rspress.config.ts
  e2e/fixtures/toc-id/tsconfig.json
  e2e/tests/custom-id.test.ts
  e2e/tests/toc-id.test.ts
  packages/core/package.json
  pnpm-lock.yaml
Labels: change: fix

#1606 fix: use rspress-dev as debug mode for source build plugin
  packages/core/src/node/PluginDriver.ts
  packages/shared/src/runtime-utils/index.ts
Labels: change: fix

#1608 fix(plugin-preview): dark mode card border color
  packages/plugin-preview/static/global-components/common/index.scss
Labels: change: fix

#1609 fix: performance regression of check html regex
  e2e/fixtures/inline-markdown/doc/inline/all.mdx
  e2e/tests/inline-markdown.test.ts
  packages/theme-default/src/logic/utils.ts
Labels: change: fix

#1611 feat: custom doc-layout components
  packages/document/docs/en/guide/advanced/custom-theme.mdx
  packages/document/docs/zh/guide/advanced/custom-theme.mdx
  packages/theme-default/src/layout/DocLayout/index.tsx
  packages/theme-default/src/layout/Layout/index.tsx
Labels: change: feat

#1615 perf(theme-default): reduce unnecessary lodash methods
  packages/core/package.json
  packages/core/src/node/mdx/loader.ts
  packages/theme-default/src/components/Search/SearchPanel.tsx
  packages/theme-default/src/components/SwitchAppearance/index.tsx
  packages/theme-default/src/logic/utils.ts
  pnpm-lock.yaml
Labels: change: perf

#1616 perf(shared): move `mergeDocConfig` to node utils
  packages/core/package.json
  packages/core/src/index.ts
  packages/runtime/package.json
  packages/shared/package.json
  packages/shared/src/node-utils.ts
  packages/shared/src/node-utils/merge.ts
  packages/shared/src/runtime-utils/index.ts
  pnpm-lock.yaml
Labels: change: perf

#1620 fix(theme): nav will not be displayed when scrolling to the top(#1588)
  packages/theme-default/src/logic/useHiddenNav.ts
Labels: change: fix

#1628 fix(plugin-typedoc): link error and empty dir labels in sidebar
  .changeset/heavy-pants-bake.md
  .gitignore
  e2e/fixtures/auto-nav-sidebar-no-meta/doc/api/plugin/plugin-a.mdx
  e2e/fixtures/auto-nav-sidebar-no-meta/doc/api/plugin/plugin-b.mdx
  e2e/fixtures/plugin-api-docgen/doc/index.mdx
  e2e/fixtures/plugin-api-docgen/package.json
  e2e/fixtures/plugin-api-docgen/rspress.config.ts
  e2e/fixtures/plugin-api-docgen/src/Button.ts
  e2e/fixtures/plugin-api-docgen/tsconfig.json
  e2e/fixtures/plugin-typedoc/multi/doc/_meta.json
  e2e/fixtures/plugin-typedoc/multi/doc/guide.mdx
  e2e/fixtures/plugin-typedoc/multi/doc/index.mdx
  e2e/fixtures/plugin-typedoc/multi/package.json
  e2e/fixtures/plugin-typedoc/multi/rspress.config.ts
  e2e/fixtures/plugin-typedoc/multi/src/index.ts
  e2e/fixtures/plugin-typedoc/multi/src/middleware.ts
  e2e/fixtures/plugin-typedoc/multi/tsconfig.json
  e2e/fixtures/plugin-typedoc/single/doc/_meta.json
  e2e/fixtures/plugin-typedoc/single/doc/guide.mdx
  e2e/fixtures/plugin-typedoc/single/doc/index.mdx
  e2e/fixtures/plugin-typedoc/single/package.json
  e2e/fixtures/plugin-typedoc/single/rspress.config.ts
  e2e/fixtures/plugin-typedoc/single/src/index.ts
  e2e/fixtures/plugin-typedoc/single/src/middleware.ts
  e2e/fixtures/plugin-typedoc/single/tsconfig.json
  e2e/tests/api-docgen.test.ts
  e2e/tests/auto-nav-sidebar-dir-convension.test.ts
  e2e/tests/auto-nav-sidebar-no-meta.test.ts
  e2e/tests/link.test.ts
  e2e/tests/plugin-typedoc.test.ts
  e2e/utils/getSideBar.ts
  e2e/utils/newPage.ts
  packages/core/src/node/PluginDriver.ts
  packages/plugin-auto-nav-sidebar/src/walk.ts
  packages/plugin-typedoc/src/constants.ts
  packages/plugin-typedoc/src/index.ts
  packages/plugin-typedoc/src/patch.ts
  packages/plugin-typedoc/src/sidebar.ts
  pnpm-lock.yaml
Labels: change: fix
