Repository web-infra-dev/rspress, pull requests merged in 2024-04, with the labels that each got.

#889 docs: improve community plugins
  packages/document/docs/en/plugin/official-plugins/overview.mdx
  packages/document/docs/zh/plugin/official-plugins/overview.mdx
Labels: change: docs

#890 docs: support for open graph
  packages/document/docs/public/og-image.png
  packages/document/package.json
  packages/document/rspress.config.ts
  pnpm-lock.yaml
Labels: change: docs

#892 docs: improve extend build guide
  packages/document/docs/en/api/config/config-build.mdx
  packages/document/docs/en/guide/advanced/extend-build.mdx
  packages/document/docs/zh/api/config/config-build.mdx
  packages/document/docs/zh/guide/advanced/extend-build.mdx
Labels: change: docs

#851 feat(plugin-rss): RSS Plugin
  .changeset/tiny-zoos-beg.md
  e2e/fixtures/plugin-rss/doc/blog/bar.md
  e2e/fixtures/plugin-rss/doc/blog/foo.md
  e2e/fixtures/plugin-rss/doc/index.md
  e2e/fixtures/plugin-rss/doc/releases/1.0.0.md
  e2e/fixtures/plugin-rss/fixture.json
  e2e/fixtures/plugin-rss/package.json
  e2e/fixtures/plugin-rss/rspress.config.ts
  e2e/fixtures/plugin-rss/tsconfig.json
  e2e/tests/plugin-rss.test.ts
  packages/document/docs/en/plugin/official-plugins/_meta.json
  packages/document/docs/en/plugin/official-plugins/overview.mdx
  packages/document/docs/en/plugin/official-plugins/rss.mdx
  packages/document/docs/zh/plugin/official-plugins/_meta.json
  packages/document/docs/zh/plugin/official-plugins/overview.mdx
  packages/document/docs/zh/plugin/official-plugins/rss.mdx
  packages/plugin-rss/LICENSE
  packages/plugin-rss/README.md
  packages/plugin-rss/modern.config.ts
  packages/plugin-rss/package.json
  packages/plugin-rss/src/exports.ts
  packages/plugin-rss/src/feed.ts
  packages/plugin-rss/src/index.ts
  packages/plugin-rss/src/internals/index.ts
  packages/plugin-rss/src/internals/lang.ts
  packages/plugin-rss/src/internals/node.ts
  packages/plugin-rss/src/internals/type.ts
  packages/plugin-rss/src/options.ts
  packages/plugin-rss/src/plugin-rss.ts
  packages/plugin-rss/src/type.ts
  packages/plugin-rss/static/global-components/FeedsAnnotations.tsx
  packages/plugin-rss/tests/tsconfig.json
  packages/plugin-rss/tsconfig.json
  packages/plugin-rss/tsconfig.runtime.json
  packages/plugin-rss/tsconfig.tools.json
  packages/plugin-rss/vitest.config.ts
  pnpm-lock.yaml
Labels: change: feat

#878 fix: avoid flash of theme appearance in dev mode
  .changeset/eighty-experts-camp.md
  .changeset/great-boats-notice.md
  packages/core/src/node/build.ts
  packages/core/src/node/constants.ts
  packages/core/src/node/initRsbuild.ts
Labels: change: fix

#879 fix: avoid flash of navbar images (logo and theme icon)
  .changeset/thin-houses-flash.md
  packages/theme-default/src/components/Nav/NavBarTitle.tsx
  packages/theme-default/src/components/SwitchAppearance/index.tsx
  packages/theme-default/src/logic/utils.ts
Labels: change: fix

#877 feat: respond to the change of system theme appearance
  .changeset/perfect-islands-shave.md
  packages/core/src/runtime/clientEntry.tsx
  packages/theme-default/src/components/SwitchAppearance/index.tsx
  packages/theme-default/src/logic/index.ts
  packages/theme-default/src/logic/useAppearance.ts
  packages/theme-default/src/logic/useHandler.ts
  packages/theme-default/src/logic/useMediaQuery.ts
  packages/theme-default/src/logic/useStorageValue.ts
Labels: change: feat

#910 fix: invalid exports.types field
  packages/plugin-rss/package.json
  packages/shared/package.json
Labels: change: fix

#912 docs(plugin-rss): add multiple links example
  packages/document/docs/en/plugin/official-plugins/rss.mdx
  packages/document/docs/zh/plugin/official-plugins/rss.mdx
Labels: change: docs

#913 fix(plugin-rss): invalid link rel type
  e2e/tests/plugin-rss.test.ts
  packages/document/docs/en/plugin/official-plugins/rss.mdx
  packages/document/docs/zh/plugin/official-plugins/rss.mdx
  packages/plugin-rss/static/global-components/FeedsAnnotations.tsx
Labels: change: fix

#917 fix(theme): homepage mask based on logo vertical centering
  .changeset/nasty-carrots-share.md
  packages/theme-default/src/components/HomeHero/index.module.scss
  packages/theme-default/src/components/HomeHero/index.tsx
Labels: change: fix

#894 feat: support overviewHeaders and subPage overview
  .changeset/loud-cameras-occur.md
  .changeset/polite-swans-reply.md
  e2e/fixtures/auto-nav-sidebar/doc/_meta.json
  e2e/fixtures/auto-nav-sidebar/doc/api/_meta.json
  e2e/fixtures/auto-nav-sidebar/doc/api/client-api/_meta.json
  e2e/fixtures/auto-nav-sidebar/doc/api/client-api/api-components.mdx
  e2e/fixtures/auto-nav-sidebar/doc/api/client-api/api-runtime.mdx
  e2e/fixtures/auto-nav-sidebar/doc/api/client-api/index.mdx
  e2e/fixtures/auto-nav-sidebar/doc/api/commands.mdx
  e2e/fixtures/auto-nav-sidebar/doc/api/config.mdx
  e2e/fixtures/auto-nav-sidebar/doc/api/config/_meta.json
  e2e/fixtures/auto-nav-sidebar/doc/api/config/config-basic.mdx
  e2e/fixtures/auto-nav-sidebar/doc/api/config/config-build.mdx
  e2e/fixtures/auto-nav-sidebar/doc/api/config/config-frontmatter.mdx
  e2e/fixtures/auto-nav-sidebar/doc/api/config/config-theme.mdx
  e2e/fixtures/auto-nav-sidebar/doc/api/index.mdx
  e2e/tests/auto-nav-sidebar.test.ts
  packages/document/docs/en/api/config/config-frontmatter.mdx
  packages/document/docs/en/fragments/internal-components.mdx
  packages/document/docs/en/guide/basic/auto-nav-sidebar.mdx
  packages/document/docs/en/guide/default-theme/overview-page.mdx
  packages/document/docs/zh/api/config/config-frontmatter.mdx
  packages/document/docs/zh/fragments/internal-components.mdx
  packages/document/docs/zh/guide/basic/auto-nav-sidebar.mdx
  packages/document/docs/zh/guide/default-theme/overview-page.mdx
  packages/plugin-auto-nav-sidebar/src/type.ts
  packages/plugin-auto-nav-sidebar/src/utils.ts
  packages/plugin-auto-nav-sidebar/src/walk.ts
  packages/shared/src/types/defaultTheme.ts
  packages/shared/src/types/index.ts
  packages/theme-default/src/components/Overview/index.module.scss
  packages/theme-default/src/components/Overview/index.tsx
Labels: change: feat

#904 feat: Support `srcset` and `sizes` for homepage image
  .changeset/lazy-cars-tan.md
  e2e/fixtures/page-type-home/doc/index.md
  e2e/fixtures/page-type-home/package.json
  e2e/fixtures/page-type-home/rspress.config.ts
  e2e/fixtures/page-type-home/tsconfig.json
  e2e/tests/page-type-home.test.ts
  packages/document/docs/en/api/config/config-frontmatter.mdx
  packages/document/docs/zh/api/config/config-frontmatter.mdx
  packages/shared/src/types/index.ts
  packages/theme-default/src/components/HomeHero/index.tsx
  pnpm-lock.yaml
Labels: change: feat

#929 docs(plugins): add @rspress/plugin-api-docgen
  .changeset/thick-lobsters-run.md
  packages/document/docs/en/plugin/official-plugins/_meta.json
  packages/document/docs/en/plugin/official-plugins/api-docgen.mdx
  packages/document/docs/en/plugin/official-plugins/overview.mdx
  packages/document/docs/zh/plugin/official-plugins/_meta.json
  packages/document/docs/zh/plugin/official-plugins/api-docgen.mdx
  packages/document/docs/zh/plugin/official-plugins/overview.mdx
Labels: change: docs

#930 fix: add builtin rsbuild plugins before thrid party plugins
  packages/core/src/node/initRsbuild.ts
Labels: change: fix

#926 feat(plugin-rss): sort rss items by publishing date in decreasing order
  .changeset/modern-olives-swim.md
  e2e/fixtures/plugin-rss/doc/blog/bar.md
  e2e/fixtures/plugin-rss/doc/blog/foo.md
  e2e/tests/plugin-rss.test.ts
  packages/document/docs/en/plugin/official-plugins/rss.mdx
  packages/document/docs/zh/plugin/official-plugins/rss.mdx
  packages/plugin-rss/src/internals/lang.ts
  packages/plugin-rss/src/internals/type.ts
  packages/plugin-rss/src/options.ts
  packages/plugin-rss/src/plugin-rss.ts
  packages/plugin-rss/src/type.ts
Labels: change: feat

#932 docs: parseToolOptions in @rspress/plugin-api-docgen
  packages/document/docs/en/plugin/official-plugins/api-docgen.mdx
  packages/document/docs/zh/plugin/official-plugins/api-docgen.mdx
Labels: change: docs

#943 docs: Replace the outdated @rspress/plugin-last-updated api lastUpdat…
  packages/document/docs/en/plugin/official-plugins/last-updated.mdx
  packages/document/docs/zh/plugin/official-plugins/last-updated.mdx
Labels: change: docs

#940 fix: avoid unexpected changes to searchHooks
  packages/core/src/node/runtimeModule/siteData/index.ts
Labels: change: fix

#960 feat: support code transform in preview plugin
  e2e/fixtures/custom-plugin/blog/index.md
  e2e/fixtures/custom-plugin/doc/index.mdx
  e2e/fixtures/custom-plugin/package.json
  e2e/fixtures/custom-plugin/plugin.ts
  e2e/fixtures/custom-plugin/rspress.config.ts
  e2e/fixtures/custom-plugin/tsconfig.json
  e2e/fixtures/plugin-preview/doc/component.jsx
  e2e/fixtures/plugin-preview/doc/index.mdx
  e2e/fixtures/plugin-preview/package.json
  e2e/fixtures/plugin-preview/rspress.config.ts
  e2e/fixtures/plugin-preview/tsconfig.json
  e2e/fixtures/plugin/doc/components/component.jsx
  e2e/fixtures/plugin/doc/components/guide.mdx
  e2e/tests/custom-plugin.test.ts
  e2e/tests/plguin-preview.test.ts
  packages/document/docs/en/plugin/official-plugins/preview.mdx
  packages/document/docs/zh/plugin/official-plugins/preview.mdx
  packages/plugin-preview/src/ast-helpers.ts
  packages/plugin-preview/src/index.ts
  packages/plugin-preview/src/remarkPlugin.ts
  packages/plugin-preview/src/types.ts
  packages/plugin-preview/src/utils.ts
  pnpm-lock.yaml
Labels: change: feat

#957 feat: support separate search indexes by version
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/core/src/node/searchIndex.ts
  packages/shared/src/types/index.ts
  packages/theme-default/src/components/Search/SearchPanel.tsx
  packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
  packages/theme-default/src/components/Search/logic/types.ts
  packages/theme-default/src/logic/useFullTextSearch.ts
Labels: change: feat

#955 fix(core): normalizeRoutePath remove only known extensions
  packages/core/src/node/mdx/remarkPlugins/checkDeadLink.ts
  packages/core/src/node/route/RouteService.test.ts
  packages/core/src/node/route/RouteService.ts
  packages/core/src/node/runtimeModule/routeData.ts
Labels: change: fix

#963 feat(api-docgen): support more config to init parser instance
  packages/document/docs/en/plugin/official-plugins/api-docgen.mdx
  packages/document/docs/zh/plugin/official-plugins/api-docgen.mdx
  packages/plugin-api-docgen/package.json
  packages/plugin-api-docgen/src/docgen.ts
  packages/plugin-api-docgen/src/types.ts
Labels: change: feat

#934 fix: url containing dots were not correctly normalized with .html extension
  .changeset/spotty-pumas-travel.md
  packages/shared/src/runtime-utils/index.test.ts
  packages/shared/src/runtime-utils/index.ts
Labels: change: fix

#966 fix: log error when scan sidemeta
  packages/plugin-auto-nav-sidebar/src/walk.ts
Labels: change: fix

#968 fix: checkDeadLinks when mdxRs is set to false
  packages/core/src/node/route/RouteService.ts
Labels: change: fix

#972 fix: page crashes if Tabs has single Tab child
  e2e/fixtures/tabs-component/doc/index.mdx
  e2e/fixtures/tabs-component/package.json
  e2e/fixtures/tabs-component/rspress.config.ts
  e2e/tests/tabs-component.test.ts
  packages/theme-default/src/components/Tabs/index.tsx
  pnpm-lock.yaml
Labels: change: fix

#970 feat: add divider border for h2 title
  packages/theme-default/src/layout/DocLayout/docComponents/title.tsx
  packages/theme-default/src/styles/vars.css
Labels: change: feat

#973 fix: Tabs component children contains linebreak or with no tab
  e2e/fixtures/tabs-component/doc/index.mdx
  e2e/tests/tabs-component.test.ts
  packages/theme-default/src/components/Tabs/index.tsx
Labels: change: fix

#969 fix(theme): set outline title in mobile view to `themeConfig.outlineTitle`
  .changeset/green-eagles-hide.md
  packages/theme-default/src/components/LocalSideBar/index.tsx
  packages/theme-default/src/layout/DocLayout/index.tsx
Labels: change: fix

#962 docs: versioned search
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/en/guide/default-theme/multi-version.mdx
Labels: change: docs

#975 docs: search.versioned zh doc
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/en/guide/default-theme/multi-version.mdx
  packages/document/docs/en/plugin/official-plugins/api-docgen.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/document/docs/zh/guide/default-theme/multi-version.mdx
  packages/document/docs/zh/plugin/official-plugins/api-docgen.mdx
Labels: change: docs

#976 fix(theme): remove invalid `className`
  .changeset/real-cobras-double.md
  packages/theme-default/src/components/Nav/index.tsx
  packages/theme-default/src/components/NavScreen/index.tsx
Labels: change: fix

#980 ✨ feat(route): Update home page title with frontmatter titleSuffix
  packages/document/docs/en/api/config/config-frontmatter.mdx
  packages/document/docs/en/index.md
  packages/document/docs/zh/api/config/config-frontmatter.mdx
  packages/document/docs/zh/index.md
  packages/shared/src/types/index.ts
  packages/theme-default/src/layout/Layout/index.tsx
Labels: change: feat

#981 feat: improve table border style in dark mode
  packages/theme-default/src/layout/DocLayout/docComponents/table.tsx
Labels: change: feat

#979 fix(modern-plugin): improve ignore for auto sidebar
  packages/modern-plugin-rspress/src/lanchDoc.ts
Labels: change: fix

#982 fix: sidebar not display using cleanUrls: true when visit with .html suffix
  packages/shared/src/runtime-utils/index.test.ts
  packages/shared/src/runtime-utils/index.ts
Labels: change: fix

#983 docs: enable cleanUrls for website
  packages/document/docs/en/guide/start/introduction.mdx
  packages/document/docs/zh/guide/start/introduction.mdx
  packages/document/rspress.config.ts
Labels: change: docs

#985 style: modify font-synthesis from none to style
  packages/theme-default/src/styles/base.css
Labels: change: feat

#988 docs: improve `markdown.highlightLanguages`
  packages/document/docs/en/api/config/config-build.mdx
  packages/document/docs/zh/api/config/config-build.mdx
Labels: change: docs

#990 docs: fix plugin-playground typo
  packages/document/docs/zh/plugin/official-plugins/playground.mdx
Labels: change: docs

#1000 docs: fix Runner typo
  packages/document/docs/en/plugin/official-plugins/playground.mdx
Labels: change: docs

#989 fix: tailwind preflight style pollution
  .changeset/serious-ways-kneel.md
  packages/theme-default/src/components/LocalSideBar/index.scss
  packages/theme-default/src/components/Nav/index.module.scss
  packages/theme-default/src/styles/base.css
  packages/theme-default/src/styles/preflight.css
Labels: change: fix

#1007 fix: crash when page not found & using multiVersion
  packages/core/src/runtime/App.tsx
Labels: change: fix

#993 fix(theme-default): sidebar incorrect active
  packages/theme-default/src/logic/sideEffects.ts
Labels: change: fix

#997 feat: apply i18n searchPlaceholderText to SearchPanel component
  packages/theme-default/src/components/Search/SearchPanel.tsx
Labels: change: feat

#1013 fix: button background color style
  packages/theme-default/src/components/NavHambmger/index.module.scss
  packages/theme-default/src/components/NavScreen/index.module.scss
  packages/theme-default/src/components/Search/index.module.scss
  packages/theme-default/src/layout/DocLayout/docComponents/code/index.module.scss
Labels: change: fix

#1009 style: use items-center in hero block
  .changeset/plenty-birds-matter.md
  packages/theme-default/src/components/HomeHero/index.tsx
Labels: change: feat

#1014 docs: add hero text line breaks guide
  packages/document/docs/en/api/config/config-frontmatter.mdx
  packages/document/docs/en/fragments/internal-components.mdx
  packages/document/docs/zh/api/config/config-frontmatter.mdx
  packages/document/docs/zh/fragments/internal-components.mdx
Labels: change: docs

#1015 feat: support configuring titleSuffix in all page types
  e2e/fixtures/title-suffix/doc/foo.md
  e2e/fixtures/title-suffix/doc/index.md
  e2e/fixtures/title-suffix/package.json
  e2e/fixtures/title-suffix/rspress.config.ts
  e2e/fixtures/title-suffix/tsconfig.json
  e2e/tests/title-suffix.test.ts
  packages/document/docs/en/api/config/config-frontmatter.mdx
  packages/document/docs/en/index.md
  packages/document/docs/zh/api/config/config-frontmatter.mdx
  packages/document/docs/zh/index.md
  packages/theme-default/src/layout/Layout/index.tsx
  pnpm-lock.yaml
Labels: change: feat

#1016 style: optimize inline code and link style
  .changeset/neat-rabbits-hide.md
  packages/theme-default/src/layout/DocLayout/docComponents/index.module.scss
  packages/theme-default/src/styles/code.css
  packages/theme-default/src/styles/vars.css
Labels: change: feat

#1019 fix: client compile error when set react-dom/server alias
  packages/core/src/node/initRsbuild.ts
  packages/core/src/node/utils/detectReactVersion.ts
Labels: change: fix

#1021 fix(theme-default): display sidebar emphasis text
  packages/core/package.json
  packages/theme-default/src/logic/utils.ts
  pnpm-lock.yaml
Labels: change: fix

#1018 feat(theme-default): sync tab choices
  packages/theme-default/src/components/PackageManagerTabs/index.tsx
  packages/theme-default/src/components/Tabs/index.tsx
Labels: change: feat

#1025 feat: support tooltip when hover aside item
  packages/theme-default/src/components/Aside/index.tsx
  packages/theme-default/src/logic/utils.ts
Labels: change: feat

#1024 feat: support single file overview in order
  e2e/fixtures/auto-nav-sidebar/doc/api/_meta.json
  e2e/fixtures/auto-nav-sidebar/doc/api/single-page.mdx
  e2e/tests/auto-nav-sidebar.test.ts
  packages/theme-default/src/components/Overview/index.tsx
Labels: change: feat

#1028 fix: tabData undefined when syncIndex
  .changeset/famous-bees-care.md
  packages/theme-default/src/logic/TabDataContext.ts
Labels: change: fix

#1033 fix(deps): bump Rsbuild v0.6.7
  packages/cli/package.json
  packages/core/package.json
  packages/plugin-preview/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: fix

#1023 fix(theme-default): changing language and version on 404 page does nothing
  packages/shared/src/runtime-utils/index.ts
  packages/theme-default/src/components/Nav/menuDataHooks.tsx
Labels: change: fix

#1030 fix(theme-default): 404 page doesn't back to home of current lang and version
  packages/core/src/runtime/App.tsx
  packages/theme-default/src/layout/NotFountLayout/index.tsx
Labels: change: fix

#1035 fix: filename contain extname like suffix
  e2e/fixtures/auto-nav-sidebar/doc/api/config/_meta.json
  e2e/fixtures/auto-nav-sidebar/doc/api/config/config-extname.json.mdx
  e2e/tests/auto-nav-sidebar.test.ts
  packages/plugin-auto-nav-sidebar/src/utils.ts
  packages/plugin-auto-nav-sidebar/src/walk.ts
Labels: change: fix

#1038 fix: sidebar with link collapse
  packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
Labels: change: fix

#1042 fix: module doc should scan _meta.json
  .changeset/five-eels-smoke.md
  packages/modern-plugin-rspress/src/lanchDoc.ts
Labels: change: fix

#1046 feat(style): improve links style in dark mode
  packages/theme-default/src/components/Aside/index.scss
  packages/theme-default/src/components/Aside/index.tsx
  packages/theme-default/src/components/Link/index.module.scss
  packages/theme-default/src/components/Nav/index.module.scss
  packages/theme-default/src/components/Overview/index.module.scss
  packages/theme-default/src/components/Sidebar/SidebarItem.tsx
  packages/theme-default/src/components/Sidebar/index.module.scss
  packages/theme-default/src/components/Tabs/index.module.scss
  packages/theme-default/src/layout/DocLayout/docComponents/index.module.scss
  packages/theme-default/src/styles/vars.css
Labels: change: feat
