Repository web-infra-dev/rspress, pull requests merged in 2024-10, with the labels that each got.

#1447 feat(theme-default): adjust the color contrast in dark mode
  packages/document/docs/en/guide/start/introduction.mdx
  packages/theme-default/src/styles/vars.css
Labels: change: feat

#1453 docs: enable sitemap plugin
  packages/document/docs/en/plugin/community-plugins/overview.mdx
  packages/document/docs/zh/plugin/community-plugins/overview.mdx
  packages/document/package.json
  packages/document/rspress.config.ts
  pnpm-lock.yaml
Labels: change: docs

#1456 feat: enable Rsbuild CLI shortcuts
  packages/core/src/node/initRsbuild.ts
Labels: change: feat

#1451 feat(theme-default): children, outline and fixes for Badge
  packages/document/docs/en/api/client-api/api-components.mdx
  packages/document/docs/en/fragments/builtin-components.mdx
  packages/document/docs/en/guide/default-theme/components.mdx
  packages/document/docs/zh/api/client-api/api-components.mdx
  packages/document/docs/zh/fragments/builtin-components.mdx
  packages/document/docs/zh/guide/default-theme/components.mdx
  packages/theme-default/src/components/Badge/index.module.scss
  packages/theme-default/src/components/Badge/index.tsx
Labels: change: feat

#1459 fix: unexpect pending when title include -number
  e2e/fixtures/title-number/doc/index.mdx
  e2e/fixtures/title-number/package.json
  e2e/fixtures/title-number/rspress.config.ts
  e2e/fixtures/title-number/tsconfig.json
  e2e/tests/title-number.test.ts
  packages/core/src/node/runtimeModule/siteData/extractPageData.ts
  pnpm-lock.yaml
Labels: change: fix

#1472 feat: support RSS html feedline
  packages/core/src/node/runtimeModule/siteData/extractPageData.ts
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/plugin-rss/src/feed.ts
  packages/shared/src/types/index.ts
  packages/theme-default/src/logic/useEditLink.ts
Labels: change: feat

#1474 perf: do not emit assets in SSR
  packages/core/src/node/initRsbuild.ts
Labels: change: perf

#1476 fix(deps): unpin Rsbuild to allow automatic patch upgrade
  e2e/fixtures/plugin-shiki/package.json
  packages/cli/package.json
  packages/core/package.json
  packages/plugin-preview/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: fix

#1478 fix(perf): remove the _html size in runtime module
  packages/core/src/node/runtimeModule/siteData/extractPageData.ts
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/runtime/src/hooks.ts
Labels: change: fix

#1469 feat(@rspress/plugin-container-syntax): support for gitHub markdown alert syntax!
  packages/plugin-container-syntax/src/remarkPlugin.ts
  packages/plugin-container-syntax/tests/__snapshots__/index.test.ts.snap
  packages/plugin-container-syntax/tests/index.test.ts
Labels: change: feat

#1483 fix: use `Link` for `NavBarTitle`
  packages/theme-default/src/components/Nav/NavBarTitle.tsx
Labels: change: fix

#1481 fix: load i18n source without cache
  packages/core/src/node/runtimeModule/i18n.ts
Labels: change: fix

#1488 feat(theme-default): Support Filter for API Overview
  e2e/tests/i18n.test.ts
  packages/theme-default/src/components/Overview/index.tsx
Labels: change: feat

#1494 fix(plugin-container-syntax): typical markdown blockquote syntax throwing error
  e2e/fixtures/github-alert/doc/index.mdx
  e2e/fixtures/github-alert/package.json
  e2e/fixtures/github-alert/rspress.config.ts
  e2e/fixtures/github-alert/tsconfig.json
  packages/plugin-container-syntax/src/remarkPlugin.ts
  pnpm-lock.yaml
Labels: change: fix

#1497 fix(theme-default): Capitalise the 'P' in 'Next page'
  packages/theme-default/src/components/PrevNextPage/index.tsx
Labels: change: fix

#1503 fix: use front matter as overview page title
  .changeset/blue-fireants-rescue.md
  packages/document/docs/en/api/index.mdx
  packages/document/docs/en/guide/default-theme/overview-page.mdx
  packages/document/docs/zh/api/index.mdx
  packages/document/docs/zh/guide/default-theme/overview-page.mdx
  packages/theme-default/src/components/Overview/index.tsx
Labels: change: fix

#1493 feat: support location of overview and search docs
  .changeset/breezy-islands-argue.md
  .changeset/hip-bulldogs-build.md
  packages/document/docs/en/api/config/config-theme.mdx
  packages/document/docs/zh/api/config/config-theme.mdx
  packages/document/rspress.config.ts
  packages/shared/src/types/defaultTheme.ts
  packages/theme-default/src/components/Overview/index.tsx
  packages/theme-default/src/logic/useLocaleSiteData.ts
Labels: change: feat

#1507 fix: correctly iterate over plugins when using `removePlugin`
  packages/core/src/node/PluginDriver.ts
Labels: change: fix

#1511 feat: support replacement nav title
  .changeset/pink-dryers-cross.md
  packages/document/docs/en/guide/advanced/custom-theme.mdx
  packages/document/docs/zh/guide/advanced/custom-theme.mdx
  packages/theme-default/src/components/LocalSideBar/index.tsx
  packages/theme-default/src/components/Nav/index.tsx
  packages/theme-default/src/components/Sidebar/index.tsx
  packages/theme-default/src/layout/DocLayout/index.tsx
  packages/theme-default/src/layout/Layout/index.tsx
Labels: change: feat

#1512 feat: support Card and LinkCard components
  .changeset/tender-hornets-obey.md
  packages/document/docs/en/fragments/builtin-components.mdx
  packages/document/docs/zh/fragments/builtin-components.mdx
  packages/theme-default/src/components/Card/index.tsx
  packages/theme-default/src/components/LinkCard/index.module.scss
  packages/theme-default/src/components/LinkCard/index.tsx
  packages/theme-default/src/components/index.tsx
Labels: change: feat

#1517 fix: remove built-in override browserslist
  packages/core/src/node/initRsbuild.ts
Labels: change: fix

#1519 feat: add named className for sidebar component
  e2e/tests/auto-nav-sidebar.test.ts
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/document/docs/en/api/config/config-frontmatter.mdx
  packages/document/docs/zh/api/config/config-frontmatter.mdx
  packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
Labels: change: feat

#1525 fix: only reduce iterator when plugin exists
  .changeset/wise-planes-flow.md
  packages/core/src/node/PluginDriver.ts
Labels: change: fix

#1531 fix: logo dom only displays when logo exists
  .changeset/cool-lobsters-decide.md
  packages/theme-default/src/components/Nav/NavBarTitle.tsx
Labels: change: fix

#1539 fix: langRoutePrefix should end with slash
  packages/theme-default/src/logic/useLocaleSiteData.ts
Labels: change: fix
