Repository web-infra-dev/rspress, pull requests merged in 2024-05, with the labels that each got.

#1049 docs: update deploy.mdx to use node 20、pnpm 8
  packages/document/docs/en/guide/basic/deploy.mdx
  packages/document/docs/zh/guide/basic/deploy.mdx
Labels: change: docs

#1053 fix: detect file error when file is public resource
  packages/plugin-auto-nav-sidebar/src/utils.ts
Labels: change: fix

#1061 fix(deps): bump Rsbuild v0.6.11
  packages/cli/package.json
  packages/core/package.json
  packages/plugin-preview/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: fix

#1060 fix: sidebar navigate link error
  e2e/tests/auto-nav-sidebar.test.ts
  packages/plugin-auto-nav-sidebar/src/utils.ts
Labels: change: fix

#1063 fix(deps): bump Rsbuild v0.6.12
  packages/cli/package.json
  packages/core/package.json
  packages/plugin-preview/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: fix

#1066 fix(deps): bump Rsbuild v0.6.13
  .changeset/shiny-turtles-rule.md
  packages/cli/package.json
  packages/core/package.json
  packages/plugin-preview/package.json
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: fix

#1068 fix: merge duplicated border CSS
  packages/theme-default/src/layout/DocLayout/docComponents/index.module.scss
Labels: change: fix

#1069 fix: incorrect default site title
  packages/core/src/node/constants.ts
  packages/core/src/node/initRsbuild.ts
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/document/docs/zh/guide/basic/deploy.mdx
Labels: change: fix

#1072 fix: globalStyles being shaked when config some sideEffects
  e2e/fixtures/modern-js/package.json
  e2e/tests/modern-js.test.ts
  packages/core/src/node/initRsbuild.ts
Labels: change: fix

#1075 fix: SourceCode button color in dark mode
  packages/document/docs/en/plugin/official-plugins/api-docgen.mdx
  packages/document/docs/zh/plugin/official-plugins/api-docgen.mdx
  packages/theme-default/src/assets/github.svg
  packages/theme-default/src/components/SourceCode/index.tsx
Labels: change: fix

#1050 feat: automatically import highlight languages
  packages/core/package.json
  packages/core/src/global.d.ts
  packages/core/src/node/mdx/loader.ts
  packages/core/src/node/mdx/options.ts
  packages/core/src/node/runtimeModule/index.ts
  packages/core/src/node/runtimeModule/prismLanguages.ts
  packages/core/src/node/runtimeModule/siteData/extractPageData.ts
  packages/core/src/node/runtimeModule/siteData/highlightLanguages.ts
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/core/src/node/utils/detectReactVersion.ts
  packages/core/src/node/utils/flattenMdxContent.ts
  packages/core/tests/__snapshots__/prismLanguages.test.ts.snap
  packages/core/tests/prismLanguages.test.ts
  packages/core/tests/prismLanguages/extend.mdx
  packages/core/tests/prismLanguages/index.mdx
  packages/core/tests/prismLanguages/other.mdx
  packages/document/docs/en/api/config/config-build.mdx
  packages/document/docs/zh/api/config/config-build.mdx
  packages/plugin-shiki/src/shiki/pluginShiki.ts
  packages/shared/src/node-utils/loadFrontMatter.ts
  packages/shared/src/runtime-utils/index.ts
  packages/theme-default/package.json
  packages/theme-default/src/global.d.ts
  packages/theme-default/src/layout/DocLayout/docComponents/code/PrismSytaxHighlighter.tsx
  pnpm-lock.yaml
Labels: change: feat

#1076 feat: hero page image src supports light and dark
  e2e/tests/page-type-home.test.ts
  packages/document/docs/en/api/config/config-frontmatter.mdx
  packages/document/docs/en/fragments/internal-components.mdx
  packages/document/docs/zh/api/config/config-frontmatter.mdx
  packages/document/docs/zh/fragments/internal-components.mdx
  packages/shared/src/types/index.ts
  packages/theme-default/src/components/HomeHero/index.tsx
Labels: change: feat

#1082 fix: sort for prism runtime module export to pass test
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/core/tests/__snapshots__/prismLanguages.test.ts.snap
  packages/core/tests/prismLanguages.test.ts
  packages/core/tests/prismLanguages/index.mdx
Labels: change: fix

#1086 fix(deps): bump mdx-rs 0.5.7 to trim when collect title in compile
  packages/core/package.json
  pnpm-lock.yaml
Labels: change: fix

#1087 fix: not generate ssr route runtime module when client build
  packages/core/src/node/runtimeModule/routeData.ts
Labels: change: fix

#1088 fix(theme-default): the serial number of the two-digit number will become one digit. 10. -> 1.
  packages/theme-default/src/components/Sidebar/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.module.scss
Labels: change: fix

#1090 fix: link error when use keyboard to enter search result
  packages/theme-default/src/components/Search/SearchPanel.tsx
Labels: change: fix

#1091 fix: do not display no search result when search not completed
  packages/theme-default/src/components/Search/SearchPanel.tsx
Labels: change: fix

#1096 fix(theme-default): heading anchor doesn't display when no sidebar or minimum content area
  packages/theme-default/src/layout/DocLayout/docComponents/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.module.scss
Labels: change: fix

#1101 fix: tsconfig in modernjs e2e fixtures
  e2e/fixtures/modern-js/modern.config.ts
  e2e/fixtures/modern-js/tsconfig.build.json
  e2e/fixtures/modern-js/tsconfig.json
Labels: change: fix

#1104 feat: add search.loading options for remote search
  packages/shared/src/types/index.ts
  packages/theme-default/src/components/Search/SearchPanel.tsx
Labels: change: feat

#1108 fix(Tabs): correct the props type
  packages/theme-default/src/components/Tabs/index.tsx
Labels: change: fix

#1107 feat(create-rspress): enable mdx type hints by default
  packages/create-rspress/template/tsconfig.json
  packages/document/tsconfig.json
Labels: change: feat

#1110 fix(theme-default): sidebar scrollbar height error on ios safari and mask is invalid
  packages/theme-default/src/components/LocalSideBar/index.scss
  packages/theme-default/src/components/Sidebar/index.module.scss
  packages/theme-default/src/components/Sidebar/index.tsx
Labels: change: fix

#1114 feat: support custom searchNoResultsText and searchSuggestedQueryText
  packages/document/docs/en/api/config/config-theme.mdx
  packages/document/docs/zh/api/config/config-theme.mdx
  packages/document/rspress.config.ts
  packages/shared/src/types/defaultTheme.ts
  packages/theme-default/src/components/Search/NoSearchResult.tsx
  packages/theme-default/src/logic/useLocaleSiteData.ts
Labels: change: feat

#1119 docs: default theme export
  packages/document/docs/en/guide/advanced/custom-theme.mdx
  packages/document/docs/zh/guide/advanced/custom-theme.mdx
Labels: change: docs

#1085 feat: bump Rsbuild v0.7.0
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/node/initRsbuild.ts
  packages/plugin-preview/package.json
  packages/plugin-preview/src/index.ts
  packages/shared/package.json
  pnpm-lock.yaml
Labels: change: feat

#1122 fix: page crash when switch lang in api
  e2e/fixtures/i18n/doc/en/_meta.json
  e2e/fixtures/i18n/doc/en/api/index.mdx
  e2e/fixtures/i18n/doc/zh/_meta.json
  e2e/fixtures/i18n/doc/zh/api/index.mdx
  e2e/tests/i18n.test.ts
  packages/theme-default/src/components/Overview/index.tsx
Labels: change: fix

#1124 style: modify link style in container
  packages/plugin-container-syntax/container.css
Labels: change: feat

#1129 fix: search item click target set
  packages/theme-default/src/components/Search/SearchPanel.tsx
Labels: change: fix

#1127 fix: cmd+k search issue
  packages/theme-default/src/components/Search/SearchPanel.tsx
Labels: change: fix

#1128 fix: search result duplicate when keyword contains multiple langs
  packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
Labels: change: fix

#1133 fix: multi tab search
  packages/theme-default/src/components/Search/SearchPanel.tsx
Labels: change: fix

#1135 fix: virtual-search-hooks import error
  packages/theme-default/src/components/Search/SearchPanel.tsx
Labels: change: fix
