Repository web-infra-dev/rspress, pull requests merged in 2024-12, with the labels that each got.

#1636 fix(plugin-client-redirects): missing `@rspress/shared` dependency
  packages/plugin-client-redirects/package.json
  pnpm-lock.yaml
Labels: change: fix

#1642 fix(theme): Overview component cannot be used when using base
  .changeset/gold-spiders-hide.md
  e2e/fixtures/nested-overview/rspress.config.ts
  e2e/tests/nested-overview.test.ts
  packages/plugin-auto-nav-sidebar/src/walk.ts
  packages/shared/src/runtime-utils/index.ts
  packages/theme-default/src/components/Overview/utils.ts
Labels: change: fix

#1643 feat: add support for React 19
  .changeset/loud-fans-wait.md
  e2e/fixtures/react-19/doc/index.mdx
  e2e/fixtures/react-19/package.json
  e2e/fixtures/react-19/rspress.config.ts
  e2e/fixtures/react-19/tsconfig.json
  e2e/tests/react-19.test.ts
  packages/core/src/node/initRsbuild.ts
  packages/core/src/node/utils/detectReactVersion.ts
  packages/core/src/runtime/clientEntry.tsx
  packages/document/package.json
  packages/runtime/src/Content.tsx
  pnpm-lock.yaml
Labels: change: feat

#1650 fix: add overflow-wrap to break long words
  packages/theme-default/src/styles/base.css
Labels: change: fix

#1654 fix(plugin-preview): do not ignore node_modules in `watchOptions`
  .changeset/old-rings-warn.md
  packages/plugin-preview/src/index.ts
Labels: change: fix

#1648 fix(plugin-preview): dev-server is not running
  packages/plugin-preview/src/index.ts
Labels: change: fix

#1656 fix(shared): `mergeDocConfig` should dynamic import lodash-es
  packages/shared/src/node-utils/merge.ts
Labels: change: fix

#1660 docs: `head` config only takes effect in production mode
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
Labels: change: docs

#1661 docs: add `lang` config
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/en/guide/default-theme/i18n.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/document/docs/zh/guide/default-theme/i18n.mdx
  packages/shared/src/types/index.ts
Labels: change: docs

#1662 perf: remove `node-fetch` polyfill
  packages/cli/bin/rspress.js
  packages/core/package.json
  packages/core/src/node/searchIndex.ts
  packages/plugin-api-docgen/package.json
  packages/plugin-playground/package.json
  pnpm-lock.yaml
Labels: change: perf

#1670 fix: add code wrapping support for shiki highlighting
  e2e/tests/plugin-shiki.test.ts
  packages/theme-default/src/layout/DocLayout/docComponents/code/index.tsx
Labels: change: fix

#1671 fix: codeWrap code element instead
  e2e/tests/plugin-shiki.test.ts
  packages/theme-default/src/layout/DocLayout/docComponents/code/index.tsx
Labels: change: fix

#1556 feat: display title in frontmatter as heading fallback
  e2e/fixtures/heading-title/doc/guide.md
  e2e/fixtures/heading-title/package.json
  e2e/fixtures/heading-title/rspress.config.ts
  e2e/fixtures/heading-title/tsconfig.json
  e2e/tests/heading-title.test.ts
  packages/core/src/node/mdx/loader.ts
  packages/core/src/runtime/App.tsx
  packages/document/docs/en/api/config/config-theme.mdx
  packages/document/docs/zh/api/config/config-theme.mdx
  packages/shared/src/types/defaultTheme.ts
  packages/shared/src/types/index.ts
  packages/theme-default/package.json
  packages/theme-default/src/layout/DocLayout/index.tsx
  pnpm-lock.yaml
Labels: change: feat

#1675 fix(siderbar): sidebar is not stable in dev and sometimes is set by h1 in md
  e2e/tests/heading-title.test.ts
  packages/theme-default/src/components/Sidebar/SidebarItem.tsx
  packages/theme-default/src/layout/DocLayout/docComponents/title.tsx
Labels: change: fix

#1683 fix(plugin-auto-nav-sidebar): dir name contain dot
  e2e/fixtures/auto-nav-sidebar-issue-1682/docs/010.sub-directory/013.second-sub-directory/index.md
  e2e/fixtures/auto-nav-sidebar-issue-1682/docs/010.sub-directory/013.second-sub-directory/test.md
  e2e/fixtures/auto-nav-sidebar-issue-1682/docs/010.sub-directory/index.md
  e2e/fixtures/auto-nav-sidebar-issue-1682/docs/_meta.json
  e2e/fixtures/auto-nav-sidebar-issue-1682/docs/index.md
  e2e/fixtures/auto-nav-sidebar-issue-1682/package.json
  e2e/fixtures/auto-nav-sidebar-issue-1682/rspress.config.ts
  e2e/fixtures/auto-nav-sidebar-issue-1682/tsconfig.json
  e2e/tests/auto-nav-sidebar-issue-1682.test.ts
  packages/plugin-auto-nav-sidebar/src/utils.ts
  pnpm-lock.yaml
Labels: change: fix

#1707 fix(CLI): remove node flag from shebang
  packages/cli/bin/rspress.js
Labels: change: fix

#1712 fix: close hamburger menu when click on item on mobile
  e2e/fixtures/nav-link-item-with-hash/doc/index.mdx
  e2e/fixtures/nav-link-item-with-hash/rspress.config.ts
  e2e/tests/nav-link-item-with-hash.test.ts
  packages/theme-default/src/components/Link/index.tsx
  packages/theme-default/src/components/Nav/NavMenuSingleItem.tsx
  packages/theme-default/src/components/Nav/index.tsx
  packages/theme-default/src/components/NavHambmger/index.tsx
  packages/theme-default/src/components/NavScreen/index.tsx
Labels: change: fix

#1715 fix(plugin-preview): should use correct default previewMode
  packages/plugin-preview/src/index.ts
Labels: change: fix

#1716 fix(plugin-api-docgen): search index should include generated API doc
  e2e/tests/api-docgen.test.ts
  e2e/utils/search.ts
  packages/plugin-api-docgen/src/index.ts
  packages/theme-default/src/components/Search/SearchPanel.tsx
  packages/theme-default/src/components/Search/SuggestItem.tsx
Labels: change: fix

#1719 fix: navbar should be sticky on mobile when `hideNavbar` to never
  e2e/fixtures/nav-link-item-with-hash/doc/index.mdx
  e2e/fixtures/nav-link-item-with-hash/rspress.config.ts
  e2e/tests/nav-link-item-with-hash.test.ts
  packages/theme-default/src/components/Nav/index.tsx
Labels: change: fix
