Repository web-infra-dev/rspress, pull requests merged in 2025-09, with the labels that each got.

#2536 fix(core): allow user can deploy to both `http://a.com/base/` and `http://a.com/base`
  e2e/fixtures/with-base/doc/en/index.md
  e2e/fixtures/with-base/doc/en/index.mdx
  e2e/fixtures/with-base/doc/zh/index.md
  e2e/fixtures/with-base/doc/zh/index.mdx
  e2e/fixtures/with-base/index.test.ts
  packages/core/src/runtime/ClientApp.tsx
  packages/core/src/runtime/initPageData.ts
  packages/core/src/runtime/ssrServerEntry.tsx
  packages/runtime/src/index.ts
  packages/runtime/src/utils.ts
  packages/shared/src/index.ts
  packages/shared/src/runtime-utils/utils.test.ts
  packages/shared/src/runtime-utils/utils.ts
Labels: change: fix

#2527 feat: Add a twoslash plugin
  e2e/fixtures/auto-nav-sidebar-dir-convention/index.test.ts
  e2e/fixtures/plugin-twoslash/doc/index.md
  e2e/fixtures/plugin-twoslash/index.test.ts
  e2e/fixtures/plugin-twoslash/package.json
  e2e/fixtures/plugin-twoslash/rspress.config.ts
  e2e/fixtures/plugin-twoslash/tsconfig.json
  e2e/utils/search.ts
  packages/plugin-twoslash/LICENSE
  packages/plugin-twoslash/README.md
  packages/plugin-twoslash/package.json
  packages/plugin-twoslash/rslib.config.ts
  packages/plugin-twoslash/src/index.ts
  packages/plugin-twoslash/static/global-components/TwoslashPopup.tsx
  packages/plugin-twoslash/static/global-components/elements/TwoslashPopupArrow.ts
  packages/plugin-twoslash/static/global-components/elements/TwoslashPopupContainer.ts
  packages/plugin-twoslash/static/global-components/elements/TwoslashPopupPortal.ts
  packages/plugin-twoslash/static/global-components/elements/TwoslashPopupTrigger.ts
  packages/plugin-twoslash/static/global-styles/twoslash.css
  packages/plugin-twoslash/tsconfig.json
  playwright.config.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
  website/docs/en/api/config/config-basic.mdx
  website/docs/en/plugin/official-plugins/_meta.json
  website/docs/en/plugin/official-plugins/twoslash.mdx
  website/docs/zh/api/config/config-basic.mdx
  website/docs/zh/plugin/official-plugins/_meta.json
  website/docs/zh/plugin/official-plugins/twoslash.mdx
  website/package.json
  website/rspress.config.ts
Labels: change: feat

#2472 feat: enable rspack native watcher by default
  packages/core/src/node/initRsbuild.ts
Labels: change: feat

#2538 fix(plugin-twoslash): Prevent the contents of the popup from being copied when copying code
  packages/plugin-twoslash/src/index.ts
Labels: change: fix

#2542 docs: polish twoslash usage doc
  website/docs/en/guide/basic/use-mdx/code-blocks.mdx
  website/docs/en/plugin/official-plugins/twoslash.mdx
  website/docs/zh/guide/basic/use-mdx/code-blocks.mdx
  website/docs/zh/plugin/official-plugins/twoslash.mdx
Labels: change: docs

#2543 docs(plugin-twoslash): fix typo
  pnpm-lock.yaml
  website/docs/en/plugin/official-plugins/twoslash.mdx
  website/docs/zh/plugin/official-plugins/twoslash.mdx
Labels: change: docs

#2546 fix(theme-default/style): add `color: inherit` back
  packages/theme-default/src/styles/preflight.css
Labels: change: fix

#2545 fix: hmr not work
  e2e/fixtures/hmr/doc/_nav.json
  e2e/fixtures/hmr/doc/guide/_mdx-fragment.mdx
  e2e/fixtures/hmr/doc/guide/_meta.json
  e2e/fixtures/hmr/doc/guide/test.mdx
  e2e/fixtures/hmr/doc/index.mdx
  e2e/fixtures/hmr/index.test.ts
  e2e/fixtures/hmr/package.json
  e2e/fixtures/hmr/rspress.config.ts
  e2e/fixtures/hmr/tsconfig.json
  packages/core/src/node/initRsbuild.ts
  pnpm-lock.yaml
Labels: change: fix

#2544 feat(plugin-twoslash): Improve error handling with enhanced logging
  packages/plugin-twoslash/package.json
  packages/plugin-twoslash/src/index.ts
  packages/shared/src/runtime-utils/utils.ts
  pnpm-lock.yaml
Labels: change: feat

#2551 docs(codeblocks): add diff block
  website/docs/en/guide/basic/use-mdx/code-blocks.mdx
  website/docs/zh/guide/basic/use-mdx/code-blocks.mdx
Labels: change: docs

#2555 docs: add Zephyr to docs
  website/docs/en/guide/basic/deploy.mdx
Labels: change: docs

#2565 fix(plugin-playground): normalizeUrl skip protocol(#2563)
  packages/plugin-playground/src/cli/index.ts
  packages/plugin-playground/src/web/utils.ts
Labels: change: fix

#2591 docs(ui): upgrade Rspress UI part
  packages/theme-default/src/styles/index.ts
  packages/theme-default/src/styles/vars.css
  packages/theme-default/src/styles/vars/brand.scss
  website/docs/components/CssLiveCodeEditor.tsx
  website/docs/components/CssLiveCodeEditorWithTabs.tsx
  website/docs/components/CssPickerEditor.tsx
  website/docs/components/LiveCodeEditor.module.scss
  website/docs/components/LiveCodeEditor.tsx
  website/docs/en/_nav.json
  website/docs/en/ui/_meta.json
  website/docs/en/ui/vars.mdx
  website/docs/env.d.ts
  website/docs/zh/_nav.json
  website/docs/zh/ui/_meta.json
  website/docs/zh/ui/vars.mdx
  website/rspress.config.ts
Labels: change: docs

#2597 fix(ssg): Prevent the risk of naming conflicts with the user folders
  packages/core/src/node/build.ts
  packages/core/src/node/initRsbuild.ts
Labels: change: fix

#2602 fix(theme/style): some components should not be included in rp-doc
  packages/theme-default/src/components/Badge/index.tsx
  packages/theme-default/src/components/PrevNextPage/index.tsx
  packages/theme-default/src/components/SourceCode/index.tsx
  packages/theme-default/src/components/Toc/index.tsx
Labels: change: fix

#2606 fix(plugin-llms): should be compilatable to user manual nav and sidebar configuration
  packages/plugin-llms/src/normalizeMdFile.ts
  packages/plugin-llms/src/plugin.ts
Labels: change: fix

#2621 docs: fix the ui dark mode color
  website/docs/components/CssLiveCodeEditorWithTabs.tsx
Labels: change: docs

#2622 docs: adjust the folder layout
  website/docs/en/api/config/config-basic.mdx
  website/docs/en/api/config/config-frontmatter.mdx
  website/docs/en/guide/_meta.json
  website/docs/en/guide/advanced/_meta.json
  website/docs/en/guide/basic/_meta.json
  website/docs/en/guide/start/introduction.mdx
  website/docs/en/guide/use-mdx/_Border.tsx
  website/docs/en/guide/use-mdx/_button.mdx
  website/docs/en/guide/use-mdx/_escape-hatch.tsx
  website/docs/en/guide/use-mdx/_mdx-fragment.mdx
  website/docs/en/guide/use-mdx/_meta.json
  website/docs/en/guide/use-mdx/_tsx-component.tsx
  website/docs/en/guide/use-mdx/code-blocks.mdx
  website/docs/en/guide/use-mdx/components.mdx
  website/docs/en/guide/use-mdx/container.mdx
  website/docs/en/guide/use-mdx/index.mdx
  website/docs/en/guide/use-mdx/link.mdx
  website/docs/en/plugin/official-plugins/algolia.mdx
  website/docs/en/plugin/official-plugins/llms.mdx
  website/docs/en/ui/_meta.json
  website/docs/en/ui/custom-theme.mdx
  website/docs/zh/api/config/config-basic.mdx
  website/docs/zh/api/config/config-frontmatter.mdx
  website/docs/zh/guide/_meta.json
  website/docs/zh/guide/advanced/_meta.json
  website/docs/zh/guide/basic/_meta.json
  website/docs/zh/guide/start/introduction.mdx
  website/docs/zh/guide/use-mdx/_Border.tsx
  website/docs/zh/guide/use-mdx/_button.mdx
  website/docs/zh/guide/use-mdx/_escape-hatch.tsx
  website/docs/zh/guide/use-mdx/_mdx-fragment.mdx
  website/docs/zh/guide/use-mdx/_meta.json
  website/docs/zh/guide/use-mdx/_tsx-component.tsx
  website/docs/zh/guide/use-mdx/code-blocks.mdx
  website/docs/zh/guide/use-mdx/components.mdx
  website/docs/zh/guide/use-mdx/container.mdx
  website/docs/zh/guide/use-mdx/index.mdx
  website/docs/zh/guide/use-mdx/link.mdx
  website/docs/zh/plugin/official-plugins/algolia.mdx
  website/docs/zh/plugin/official-plugins/llms.mdx
  website/docs/zh/ui/_meta.json
  website/docs/zh/ui/custom-theme.mdx
Labels: change: docs

#2623 feat(theme): add prop `dlx` to `PackageManagerTabs` for `npx` `pnpm dlx` etc
  packages/theme-default/src/components/PackageManagerTabs/index.tsx
  scripts/dictionary.txt
Labels: change: feat
