Repository web-infra-dev/rspress, pull requests merged in 2025-06, with the labels that each got.

#2246 fix(theme/style): Tabs wrong margin
  packages/theme-default/src/components/Tabs/index.module.scss
Labels: change: fix

#2256 feat(mdx): add `markdown.crossCompilerCache` for speed up build process
  packages/core/rslib.config.ts
  packages/core/src/node/mdx/loader.ts
  packages/core/src/node/mdx/options.ts
  packages/core/src/node/mdx/processor.ts
  packages/core/src/node/mdx/remarkPlugins/toc.ts
  packages/core/src/node/mdx/types.ts
  packages/shared/src/types/index.ts
Labels: change: feat

#2267 feat: support async entry
  .changeset/vast-words-enter.md
  packages/core/src/node/ssg/renderPages.ts
Labels: change: feat

#2274 fix: incorrect types for `shiki-transformers` entry
  packages/core/package.json
Labels: change: fix

#2304 docs: fix Rsbuild url in README.md
  README.md
Labels: change: docs

#2314 feat(auto-nav-sidebar)!: rename the top level `_meta.json` to `_nav.json` in order to support single Nav Mode
  .gitignore
  .vscode/settings.json
  e2e/fixtures/auto-nav-sidebar-dir-convention/doc/_nav.json
  e2e/fixtures/auto-nav-sidebar-issue-1682/docs/_nav.json
  e2e/fixtures/auto-nav-sidebar-no-meta/doc/index.mdx
  e2e/fixtures/auto-nav-sidebar-no-meta/index.test.ts
  e2e/fixtures/auto-nav-sidebar/doc/_nav.json
  e2e/fixtures/i18n/doc/en/_nav.json
  e2e/fixtures/i18n/doc/zh/_nav.json
  e2e/fixtures/inline-markdown/doc/_nav.json
  e2e/fixtures/inline-markdown/doc/inline/_meta.json
  e2e/fixtures/inline-markdown/index.test.ts
  e2e/fixtures/issue-1309/docs/_nav.json
  e2e/fixtures/markdown-link/doc/_nav.json
  e2e/fixtures/multi-version/docs/v1/en/_nav.json
  e2e/fixtures/multi-version/docs/v1/zh/_nav.json
  e2e/fixtures/multi-version/docs/v2/en/_nav.json
  e2e/fixtures/multi-version/docs/v2/zh/_nav.json
  e2e/fixtures/nav-link-items-without-suffix/doc/_nav.json
  e2e/fixtures/nav-link-items/doc/_nav.json
  e2e/fixtures/nav-link/doc/_nav.json
  e2e/fixtures/nested-overview/doc/_nav.json
  e2e/fixtures/plugin-llms/doc/_nav.json
  e2e/fixtures/plugin-typedoc/multi/doc/_nav.json
  e2e/fixtures/plugin-typedoc/single/doc/_nav.json
  e2e/fixtures/replace-rules/doc/_nav.json
  e2e/fixtures/view-transition/doc/_nav.json
  packages/cli/scripts/generateJsonSchema.mjs
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-locales/en/_nav.json
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-locales/zh/_nav.json
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-meta-nav/_meta.json
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-meta-nav/_nav.json
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-meta-nav/api/api.mdx
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-meta-nav/api/guide/getting-started.mdx
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-meta-nav/api/guide/index.mdx
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-meta-nav/api/index.mdx
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-meta-nav/index.mdx
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-no-meta/index.mdx
  packages/core/src/node/auto-nav-sidebar/fixtures/docs/_nav.json
  packages/core/src/node/auto-nav-sidebar/normalize.ts
  packages/core/src/node/auto-nav-sidebar/type.ts
  packages/core/src/node/auto-nav-sidebar/walk.test.ts
  packages/core/src/node/auto-nav-sidebar/walk.ts
  packages/core/src/node/logger/hint.ts
  packages/core/src/node/utils/normalizePath.ts
  packages/document/docs/en/_nav.json
  packages/document/docs/zh/_nav.json
Labels: change: feat

#2318 fix(rehypeHeaderAnchor): trim anchor for better format with React Component
  packages/core/src/node/mdx/rehypePlugins/__snapshots__/headerAnchor.test.ts.snap
  packages/core/src/node/mdx/rehypePlugins/headerAnchor.test.ts
  packages/core/src/node/mdx/rehypePlugins/headerAnchor.ts
  packages/core/src/node/mdx/remarkPlugins/toc.ts
  packages/plugin-api-docgen/static/global-components/API.tsx
Labels: change: fix

#2327 fix: should add nav-json-schema.json and expose `rspress/shiki-transformers`
  packages/cli/package.json
  packages/cli/shiki-transformers.ts
  packages/core/rslib.config.ts
Labels: change: fix

#2332 fix(ssg): better format of mdx compile time error in SSG
  packages/core/src/node/mdx/loader.ts
  packages/core/src/node/mdx/processor.ts
  packages/core/src/node/ssg/rsbuildPluginSSG.ts
Labels: change: fix
