Repository web-infra-dev/rspress, pull requests merged in 2025-01, with the labels that each got.

#1732 fix: hiddenNavBar: auto should work
  e2e/fixtures/hide-nav-bar/doc/index.mdx
  e2e/fixtures/hide-nav-bar/package.json
  e2e/fixtures/hide-nav-bar/rspress-hide-auto.config.ts
  e2e/fixtures/hide-nav-bar/rspress.config.ts
  e2e/fixtures/hide-nav-bar/tsconfig.json
  e2e/tests/hide-nav-bar.test.ts
  e2e/tests/nav-link-item-with-hash.test.ts
  e2e/utils/runCommands.ts
  packages/theme-default/src/components/Nav/index.tsx
  pnpm-lock.yaml
Labels: change: fix

#1741 feat: support nested container syntax in list and component in mdx-js
  e2e/fixtures/github-alert-mdxjs/doc/index.mdx
  e2e/tests/github-alert-mdxjs.test.ts
  packages/core/package.json
  packages/plugin-api-docgen/package.json
  packages/plugin-container-syntax/package.json
  packages/plugin-container-syntax/src/remarkPlugin.ts
  packages/plugin-container-syntax/tests/__snapshots__/index.test.ts.snap
  packages/plugin-container-syntax/tests/index.test.ts
  packages/plugin-playground/package.json
  packages/plugin-preview/package.json
  packages/theme-default/package.json
  pnpm-lock.yaml
Labels: change: feat

#1745 feat: support nested container syntax in list in mdx-rs
  e2e/fixtures/github-alert-mdxrs/doc/index.mdx
  e2e/tests/github-alert-mdxrs.test.ts
  packages/core/package.json
  pnpm-lock.yaml
Labels: change: feat

#1747 docs: add bun to init project guide
  packages/document/docs/en/guide/start/getting-started.mdx
  packages/document/docs/zh/guide/start/getting-started.mdx
Labels: change: docs

#1746 feat: support checkLanguageParity for multilingual content validation
  packages/core/__mocks__/fs.cjs
  packages/core/__mocks__/fs/promises.cjs
  packages/core/package.json
  packages/core/src/node/build.ts
  packages/core/src/node/dev.ts
  packages/core/src/node/utils/checkLanguageParity.ts
  packages/core/tests/checkLanguageParity.test.ts
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/document/rspress.config.ts
  packages/shared/src/types/index.ts
  pnpm-lock.yaml
Labels: change: feat

#1749 feat: support nested container syntax in component in mdx-rs
  e2e/fixtures/github-alert-mdxjs/doc/index.mdx
  e2e/fixtures/github-alert-mdxrs/doc/index.mdx
  e2e/tests/github-alert-mdxjs.test.ts
  e2e/tests/github-alert-mdxrs.test.ts
  packages/core/package.json
  pnpm-lock.yaml
Labels: change: feat

#1759 feat: add bluesky socialLink
  packages/document/docs/en/api/config/config-theme.mdx
  packages/document/docs/zh/api/config/config-theme.mdx
  packages/shared/src/types/defaultTheme.ts
  packages/theme-default/src/components/SocialLinks/presetIcons.tsx
Labels: change: feat

#1761 fix: dark mode when hover LinkCard component
  packages/theme-default/src/components/LinkCard/index.module.scss
  packages/theme-default/src/components/LinkCard/index.tsx
Labels: change: fix

#1788 fix(theme-default): remove unused twitter icon
  packages/theme-default/src/components/SocialLinks/presetIcons.tsx
Labels: change: fix

#1789 perf: include social icons on demand
  packages/core/src/node/initRsbuild.ts
  packages/core/src/node/utils/getSocialIcons.ts
  packages/theme-default/src/components/SocialLinks/LinkContent.tsx
  packages/theme-default/src/components/SocialLinks/presetIcons.tsx
Labels: change: perf
