Repository web-infra-dev/rspress, pull requests merged in 2025-08, with the labels that each got.

#2432 docs(typo): update plugin-llms
  packages/document/docs/en/plugin/official-plugins/llms.mdx
  packages/document/docs/zh/plugin/official-plugins/llms.mdx
Labels: change: docs

#2433 fix(tab-list): Fix tabs scrolling when not overflowing
  packages/theme-default/src/components/Tabs/index.module.scss
Labels: change: fix

#2431 docs(v2): update code block line highlighting syntax to v2
  packages/create-rspress/template-basic/docs/guide/index.md
  packages/document/docs/en/guide/basic/use-mdx/index.mdx
  packages/document/docs/zh/guide/basic/use-mdx/index.mdx
Labels: change: docs

#2441 feat: add npm icon to social links
  packages/core/src/node/utils/getSocialIcons.ts
  packages/shared/src/types/defaultTheme.ts
Labels: change: feat

#2443 fix(plugin-llms): some md files sometimes do not emit
  packages/plugin-llms/src/llmsTxt.ts
  packages/plugin-llms/src/plugin.ts
Labels: change: fix

#2448 feat(plugin-llms)!: default value for i18n
  packages/document/docs/en/plugin/official-plugins/llms.mdx
  packages/document/docs/zh/plugin/official-plugins/llms.mdx
  packages/document/rspress.config.ts
  packages/plugin-llms/src/plugin.ts
  packages/plugin-llms/src/types.ts
Labels: change: feat

#2451 docs: add Rslint and version badges to Rstack tools table
  README.md
  scripts/dictionary.txt
Labels: change: docs

#2453 fix(auto-nav-sidebar): correct both _meta.json and _nav.json exist behavior
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v1/en/_nav.json
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v1/en/guide.md
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v1/en/guide/_meta.json
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v1/en/guide/feature.md
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v1/en/index.md
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v1/zh/_nav.json
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v1/zh/guide.md
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v1/zh/guide/_meta.json
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v1/zh/guide/feature.md
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v1/zh/index.md
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v2/en/_nav.json
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v2/en/guide.md
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v2/en/guide/_meta.json
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v2/en/guide/feature.md
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v2/en/index.md
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v2/zh/_nav.json
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v2/zh/guide.md
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v2/zh/guide/_meta.json
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v2/zh/guide/feature.md
  packages/core/src/node/auto-nav-sidebar/fixtures/docs-multi-version/v2/zh/index.md
  packages/core/src/node/auto-nav-sidebar/locales.test.ts
  packages/core/src/node/auto-nav-sidebar/walk.test.ts
  packages/core/src/node/auto-nav-sidebar/walk.ts
Labels: change: fix

#2456 fix(theme/Link): Link and HomeHero should support relative url
  e2e/fixtures/page-type-home/doc/en/_nav.json
  e2e/fixtures/page-type-home/doc/en/guide/action-1.md
  e2e/fixtures/page-type-home/doc/en/guide/action-2.md
  e2e/fixtures/page-type-home/doc/en/guide/action-3.md
  e2e/fixtures/page-type-home/doc/en/index.md
  e2e/fixtures/page-type-home/doc/zh/_nav.json
  e2e/fixtures/page-type-home/doc/zh/guide/action-1.md
  e2e/fixtures/page-type-home/doc/zh/guide/action-2.md
  e2e/fixtures/page-type-home/doc/zh/guide/action-3.md
  e2e/fixtures/page-type-home/doc/zh/index.md
  e2e/fixtures/page-type-home/index.test.ts
  e2e/fixtures/page-type-home/rspress.config.ts
  packages/document/docs/en/index.md
  packages/document/docs/zh/index.md
  packages/shared/src/runtime-utils/utils.ts
  packages/theme-default/src/components/Button/index.tsx
  packages/theme-default/src/components/HomeFeature/index.tsx
  packages/theme-default/src/components/HomeHero/index.tsx
  packages/theme-default/src/components/Link/index.tsx
  packages/theme-default/src/components/Link/useNavigate.ts
  packages/theme-default/src/components/Nav/NavBarTitle.tsx
  packages/theme-default/src/layout/NotFountLayout/index.tsx
  packages/theme-default/src/logic/useRedirect4FirstVisit.ts
Labels: change: fix

#2471 fix: export `usePage` to replace deprecated `usePageData`
  packages/runtime/src/index.ts
Labels: change: fix

#2477 feat(theme)!: add layer for base.css to support tailwind v4
  packages/theme-default/src/styles/base.css
  packages/theme-default/src/styles/index.ts
  packages/theme-default/src/styles/tailwind.css
Labels: change: feat

#2490 feat: generate Open Graph title and type tags by default
  e2e/fixtures/page-head-tags/doc/index.mdx
  e2e/fixtures/page-head-tags/doc/jane/index.mdx
  e2e/fixtures/page-head-tags/index.test.ts
  e2e/fixtures/page-head-tags/package.json
  e2e/fixtures/page-head-tags/rspress.config.ts
  package.json
  packages/theme-default/src/layout/Layout/index.tsx
  pnpm-lock.yaml
  website/docs/en/api/config/config-frontmatter.mdx
  website/docs/en/guide/basic/custom-page.mdx
  website/docs/zh/api/config/config-frontmatter.mdx
  website/docs/zh/guide/basic/custom-page.mdx
  website/rspress.config.ts
Labels: change: feat

#2491 docs: upgrade readme and add npm link to docsite
  packages/core/README.md
  website/rspress.config.ts
Labels: change: docs

#2493 fix(deps): remove unused dependencies from multiple packages
  packages/core/package.json
  packages/plugin-llms/package.json
  packages/plugin-preview/package.json
  pnpm-lock.yaml
Labels: change: fix

#2507 docs: add asset links and format with biome
  biome.json
  e2e/fixtures/auto-nav-sidebar-no-meta/doc/api/data.json
  e2e/fixtures/dynamic-toc/components/Term.tsx
  e2e/fixtures/search-algolia/theme/index.tsx
  e2e/fixtures/search-hooks/theme/index.tsx
  e2e/fixtures/search-hooks/theme/searchHooks.tsx
  e2e/fixtures/theme-css/theme/index.tsx
  packages/core/src/node/runtimeModule/searchHooks.ts
  packages/document/docs/en/guide/basic/use-mdx/link.mdx
  packages/document/docs/zh/guide/basic/use-mdx/link.mdx
  packages/plugin-preview/static/global-styles/entry.css
  scripts/generateReleasePr.mjs
  website/docs/en/guide/basic/use-mdx/link.mdx
  website/docs/zh/guide/basic/use-mdx/link.mdx
  website/rspress.config.ts
Labels: change: docs

#2508 docs(codeblocks): polish some write style
  website/docs/en/guide/basic/use-mdx/code-blocks.mdx
  website/docs/en/guide/basic/use-mdx/link.mdx
  website/docs/zh/guide/basic/use-mdx/code-blocks.mdx
Labels: change: docs

#2516 feat(plugin-llms): support `mdFiles.remarkPlugins`
  packages/plugin-llms/src/normalizeMdFile.ts
  packages/plugin-llms/src/plugin.ts
  packages/plugin-llms/src/types.ts
  website/docs/en/plugin/official-plugins/llms.mdx
  website/docs/zh/plugin/official-plugins/llms.mdx
Labels: change: feat

#2519 fix(virtual-module): should addDependencies in virtual-module for persistent cache
  packages/core/src/node/runtimeModule/pageData/createPageData.ts
  packages/core/src/node/runtimeModule/pageData/rsbuildPlugin.ts
  packages/core/src/node/runtimeModule/types.ts
  packages/core/src/runtime/env.d.ts
  packages/core/src/runtime/initPageData.ts
  packages/runtime/rslib.config.ts
  packages/runtime/src/env.d.ts
  packages/runtime/src/hooks/usePages.ts
  packages/theme-default/rslib.config.ts
  packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
  packages/theme-default/src/env.d.ts
  website/docs/en/guide/basic/use-mdx/_meta.json
Labels: change: fix

#2528 fix: command using object fully customize don't call normalize
  packages/theme-default/src/components/PackageManagerTabs/index.tsx
Labels: change: fix
