Repository web-infra-dev/rspress, pull requests merged in 2025-02, with the labels that each got.

#1797 feat: support for searching code blocks
  e2e/fixtures/search-code-blocks/doc/index.mdx
  e2e/fixtures/search-code-blocks/package.json
  e2e/fixtures/search-code-blocks/rspress.config.ts
  e2e/fixtures/search-code-blocks/tsconfig.json
  e2e/tests/search-code-blocks.test.ts
  packages/core/src/node/runtimeModule/siteData/extractPageData.ts
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/document/rspress.config.ts
  packages/shared/src/types/index.ts
  pnpm-lock.yaml
Labels: change: feat

#1808 feat(theme)!: unify socialLinks to "@iconify-json/simple-icons", smaller style and size
  packages/core/src/node/utils/getSocialIcons.ts
  packages/theme-default/src/components/Nav/index.module.scss
  packages/theme-default/src/components/SocialLinks/index.module.scss
  packages/theme-default/src/components/SocialLinks/index.tsx
Labels: change: feat

#1811 feat: preload search index when page is idle
  packages/theme-default/src/components/Search/SearchPanel.tsx
Labels: change: feat

#1812 fix: remove socialLinks twitter in redirect and document
  packages/core/src/node/utils/getSocialIcons.ts
  packages/document/docs/en/api/config/config-theme.mdx
  packages/document/docs/zh/api/config/config-theme.mdx
Labels: change: fix

#1819 feat: improve tabbed code block style
  packages/document/docs/en/fragments/builtin-components.mdx
  packages/document/docs/zh/fragments/builtin-components.mdx
  packages/theme-default/src/components/Tabs/index.module.scss
Labels: change: feat

#1826 fix(search): improve search index fetching with error handling
  packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
Labels: change: fix

#1825 fix: sidebar always matches "/"
  packages/theme-default/src/components/Search/SearchPanel.tsx
  packages/theme-default/src/logic/getSidebarDataGroup.test.ts
  packages/theme-default/src/logic/getSidebarDataGroup.ts
  packages/theme-default/src/logic/useFullTextSearch.ts
  packages/theme-default/src/logic/useSidebarData.ts
Labels: change: fix

#1829 fix(runtime): determine virtual routes by config file
  packages/core/src/node/initRsbuild.ts
  packages/runtime/src/Content.tsx
Labels: change: fix

#1836 style(theme-default): adjust layout and media query breakpoints
  packages/theme-default/src/components/Overview/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.module.scss
Labels: change: feat

#1835 docs: update README and introduction files
  README.md
  e2e/fixtures/github-alert-mdxjs/doc/index.mdx
  e2e/fixtures/github-alert-mdxrs/doc/index.mdx
  packages/cli/README.md
  packages/document/docs/en/api/config/config-frontmatter.mdx
  packages/document/docs/en/guide/start/introduction.mdx
  packages/document/docs/en/index.md
  packages/document/docs/zh/api/config/config-frontmatter.mdx
  packages/document/docs/zh/guide/start/introduction.mdx
  packages/document/docs/zh/index.md
  packages/modern-plugin-rspress/README.md
Labels: change: docs

#1837 docs: fix error of using custom search component
  packages/document/docs/en/guide/advanced/custom-theme.mdx
  packages/document/docs/zh/guide/advanced/custom-theme.mdx
Labels: change: docs

#1844 fix(core): search json path is incorrect when config.outDir is absolute
  packages/core/src/node/searchIndex.ts
Labels: change: fix

#1845 docs: update lastUpdated need commit
  packages/document/docs/en/api/config/config-theme.mdx
  packages/document/docs/en/plugin/official-plugins/last-updated.mdx
  packages/document/docs/zh/api/config/config-theme.mdx
  packages/document/docs/zh/plugin/official-plugins/last-updated.mdx
Labels: change: docs

#1846 fix(core): `route.extensions` should work
  packages/cli/src/config/loadConfigFile.ts
  packages/cli/src/constants.ts
  packages/core/src/node/route/RouteService.test.ts
  packages/core/src/node/route/RouteService.ts
  packages/core/src/node/route/fixtures/a.mdx
  packages/core/src/node/route/fixtures/basic/a.mdx
  packages/core/src/node/route/fixtures/basic/guide/b.mdx
  packages/core/src/node/route/fixtures/basic/guide/c.tsx
  packages/core/src/node/route/fixtures/basic/index.mdx
  packages/core/src/node/route/fixtures/guide/b.mdx
  packages/core/src/node/route/normalizeRoutePath.test.ts
  packages/core/src/node/route/normalizeRoutePath.ts
  packages/core/src/node/runtimeModule/siteData/extractPageData.ts
  packages/core/src/node/runtimeModule/siteData/normalizeThemeConfig.ts
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/plugin-auto-nav-sidebar/src/fixtures/docs/_meta.json
  packages/plugin-auto-nav-sidebar/src/fixtures/docs/guide/_meta.json
  packages/plugin-auto-nav-sidebar/src/fixtures/docs/guide/a.md
  packages/plugin-auto-nav-sidebar/src/fixtures/docs/guide/b.mdx
  packages/plugin-auto-nav-sidebar/src/fixtures/docs/guide/c.tsx
  packages/plugin-auto-nav-sidebar/src/fixtures/docs/guide/index.mdx
  packages/plugin-auto-nav-sidebar/src/fixtures/docs/guide/test-dir/getting-started.mdx
  packages/plugin-auto-nav-sidebar/src/fixtures/docs/guide/test-dir/index.mdx
  packages/plugin-auto-nav-sidebar/src/fixtures/docs/index.mdx
  packages/plugin-auto-nav-sidebar/src/index.ts
  packages/plugin-auto-nav-sidebar/src/walk.test.ts
  packages/plugin-auto-nav-sidebar/src/walk.ts
  packages/shared/package.json
  packages/shared/rslib.config.ts
  packages/shared/src/constants.ts
  packages/shared/src/node-utils.ts
Labels: change: fix

#1847 fix(theme): text in button should center
  packages/theme-default/src/components/Button/index.module.scss
Labels: change: fix

#1848 fix(core): supersede require with import statement in ESM output
  packages/core/rslib.config.ts
  packages/core/src/node/mdx/loader.ts
  packages/core/src/node/runtimeModule/siteData/highlightLanguages.ts
Labels: change: fix

#1853 fix(ui): SwitchApperance CLS, a flash when switching to dark mode
  packages/theme-default/src/components/NavScreen/index.tsx
Labels: change: fix

#1855 fix(mdxjs): toc item including "emphasis" and "delete" should generate
  e2e/fixtures/toc-id-mdxjs/doc/index.mdx
  e2e/fixtures/toc-id-mdxjs/package.json
  e2e/fixtures/toc-id-mdxjs/rspress.config.ts
  e2e/fixtures/toc-id-mdxjs/tsconfig.json
  e2e/fixtures/toc-id-mdxrs/doc/index.mdx
  e2e/fixtures/toc-id-mdxrs/package.json
  e2e/fixtures/toc-id-mdxrs/rspress.config.ts
  e2e/fixtures/toc-id-mdxrs/tsconfig.json
  e2e/tests/toc-id-mdxjs.test.ts
  e2e/tests/toc-id-mdxrs.test.ts
  packages/core/src/node/mdx/remarkPlugins/toc.ts
  pnpm-lock.yaml
Labels: change: fix

#1858 fix(ui): for TOC highlight, revert `setTimeout` set unbinding changes
  packages/theme-default/src/components/Aside/index.tsx
Labels: change: fix

#1862 fix(ui): prevent key events from triggering during composition
  packages/theme-default/src/components/Search/SearchPanel.tsx
Labels: change: fix

#1867 fix(search): should search JSX element code block
  e2e/fixtures/search-code-blocks/doc/index.mdx
  e2e/tests/search-code-blocks.test.ts
  e2e/utils/search.ts
  packages/core/src/node/runtimeModule/siteData/extractPageData.ts
Labels: change: fix

#1868 fix(search): for #1867, search codeBlock: false should work
  package.json
  packages/core/src/node/runtimeModule/siteData/extractPageData.test.ts
  packages/core/src/node/runtimeModule/siteData/extractPageData.ts
  pnpm-lock.yaml
  scripts/test-helper/vitest.setup.ts
  vitest.workspace.ts
Labels: change: fix

#1874 fix: shim `_dirname` in esm output
  packages/plugin-client-redirects/rslib.config.ts
  packages/plugin-playground/rslib.config.ts
Labels: change: fix

#1878 perf(size): 🔥remove package.json useless field and bundle named package.json
  e2e/fixtures/modern-js/package.json
  packages/cli/src/index.ts
  packages/core/package.json
  packages/core/src/node/build.ts
  packages/core/theme.css
  packages/modern-plugin-rspress/package.json
  packages/plugin-api-docgen/package.json
  packages/plugin-auto-nav-sidebar/package.json
  packages/plugin-client-redirects/package.json
  packages/plugin-container-syntax/package.json
  packages/plugin-last-updated/package.json
  packages/plugin-medium-zoom/package.json
  packages/plugin-preview/package.json
  packages/plugin-rss/package.json
  packages/plugin-shiki/package.json
  packages/plugin-typedoc/package.json
  packages/runtime/package.json
  packages/theme-default/package.json
Labels: change: perf

#1883 fix(globalUIComponents): fix package.json files #1878
  packages/plugin-client-redirects/package.json
  packages/plugin-client-redirects/src/index.ts
  packages/plugin-client-redirects/static/Redirect.tsx
  packages/plugin-medium-zoom/package.json
  packages/plugin-medium-zoom/src/index.ts
  packages/plugin-medium-zoom/static/MediumZoom.css
  packages/plugin-medium-zoom/static/MediumZoom.tsx
Labels: change: fix

#1890 fix(plugin-api-docgen): add Russian support
  packages/plugin-api-docgen/src/docgen.ts
  packages/plugin-api-docgen/src/index.ts
  packages/plugin-api-docgen/src/locales.ts
  packages/plugin-api-docgen/src/types.ts
Labels: change: fix
