Repository web-infra-dev/rspress, pull requests merged in 2025-03, with the labels that each got.

#1892 perf(search): add index async to avoid blocking the main thread
  packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
Labels: change: perf

#1893 perf(search): remove group calculation
  packages/theme-default/src/components/Search/SearchPanel.tsx
  packages/theme-default/src/components/Search/logic/search.ts
  packages/theme-default/src/components/Search/logic/types.ts
  packages/theme-default/src/components/Search/logic/util.ts
  packages/theme-default/src/logic/useFullTextSearch.ts
Labels: change: perf

#1895 perf: use `matchPath` rather than `matchRoutes`, remove unused group.title
  packages/runtime/src/index.ts
  packages/runtime/src/route.ts
  packages/theme-default/src/components/Overview/index.tsx
  packages/theme-default/src/components/Sidebar/index.tsx
  packages/theme-default/src/logic/getSidebarDataGroup.test.ts
  packages/theme-default/src/logic/getSidebarDataGroup.ts
  packages/theme-default/src/logic/usePrevNextPage.ts
  packages/theme-default/src/logic/useSidebarData.ts
Labels: change: perf

#1899 perf(search): improve initialization and prefetching logic
  packages/theme-default/src/components/Search/SearchPanel.tsx
  packages/theme-default/src/components/Search/logic/Provider.ts
  packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
  packages/theme-default/src/components/Search/logic/providers/RemoteProvider.ts
  packages/theme-default/src/components/Search/logic/search.ts
  scripts/dictionary.txt
Labels: change: perf

#1898 fix(search): should use `index.searchAsync`
  packages/theme-default/src/components/Search/logic/providers/LocalProvider.ts
Labels: change: fix

#1900 docs: improve Rsbuild plugin guides
  packages/document/docs/en/api/config/config-build.mdx
  packages/document/docs/en/guide/advanced/extend-build.mdx
  packages/document/docs/zh/api/config/config-build.mdx
  packages/document/docs/zh/guide/advanced/extend-build.mdx
Labels: change: docs

#1906 docs: enhance runtime API with types and dark mode usages
  packages/document/docs/en/api/client-api/api-runtime.mdx
  packages/document/docs/zh/api/client-api/api-runtime.mdx
Labels: change: docs

#1907 docs: replace generic framework references with Rspress
  packages/core/src/node/runtimeModule/siteData/normalizeThemeConfig.ts
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/en/api/config/config-build.mdx
  packages/document/docs/en/fragments/global-ui-components.mdx
  packages/document/docs/en/fragments/useI18n.mdx
  packages/document/docs/en/guide/advanced/custom-theme.mdx
  packages/document/docs/en/guide/advanced/extend-build.mdx
  packages/document/docs/en/guide/basic/auto-nav-sidebar.mdx
  packages/document/docs/en/guide/basic/custom-page.mdx
  packages/document/docs/en/guide/default-theme/i18n.mdx
  packages/document/docs/en/guide/start/introduction.mdx
  packages/document/docs/en/plugin/system/introduction.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/document/docs/zh/api/config/config-build.mdx
  packages/document/docs/zh/fragments/global-ui-components.mdx
  packages/document/docs/zh/fragments/useI18n.mdx
  packages/document/docs/zh/guide/advanced/custom-theme.mdx
  packages/document/docs/zh/guide/advanced/extend-build.mdx
  packages/document/docs/zh/guide/basic/auto-nav-sidebar.mdx
  packages/document/docs/zh/guide/basic/custom-page.mdx
  packages/document/docs/zh/guide/basic/static-assets.mdx
  packages/document/docs/zh/guide/default-theme/i18n.mdx
  packages/document/docs/zh/guide/start/introduction.mdx
  packages/document/docs/zh/plugin/system/introduction.mdx
Labels: change: docs

#1910 feat(nav): improve dropdown menu interaction
  packages/theme-default/src/components/Nav/NavMenuGroup.tsx
Labels: change: feat

#1873 feat(theme)!: use named export instead of default export, for circular imports
  e2e/fixtures/custom-layout-ui-switch/theme/index.tsx
  packages/cli/theme.ts
  packages/core/src/node/initRsbuild.ts
  packages/core/src/node/logger/hint.ts
  packages/core/src/runtime/App.tsx
  packages/core/src/runtime/clientEntry.tsx
  packages/core/theme.ts
  packages/document/docs/en/guide/advanced/custom-theme.mdx
  packages/document/docs/zh/guide/advanced/custom-theme.mdx
  packages/document/theme/index.tsx
  packages/theme-default/.theme-entry.js
  packages/theme-default/rslib.config.ts
  packages/theme-default/src/components/Aside/index.tsx
  packages/theme-default/src/components/DocFooter/index.tsx
  packages/theme-default/src/components/EditLink/index.tsx
  packages/theme-default/src/components/HomeFeature/index.tsx
  packages/theme-default/src/components/HomeHero/index.tsx
  packages/theme-default/src/components/LastUpdated/index.tsx
  packages/theme-default/src/components/Link/index.tsx
  packages/theme-default/src/components/Nav/NavBarTitle.tsx
  packages/theme-default/src/components/Nav/index.tsx
  packages/theme-default/src/components/Overview/index.tsx
  packages/theme-default/src/components/PrevNextPage/index.tsx
  packages/theme-default/src/components/Search/NoSearchResult.tsx
  packages/theme-default/src/components/Search/index.tsx
  packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
  packages/theme-default/src/components/Sidebar/SidebarItem.tsx
  packages/theme-default/src/components/Sidebar/SidebarSectionHeader.tsx
  packages/theme-default/src/components/Sidebar/index.tsx
  packages/theme-default/src/components/SourceCode/index.tsx
  packages/theme-default/src/components/Toc/index.tsx
  packages/theme-default/src/components/index.tsx
  packages/theme-default/src/index.ts
  packages/theme-default/src/layout/DocLayout/docComponents/link.tsx
  packages/theme-default/src/layout/DocLayout/index.tsx
  packages/theme-default/src/layout/Layout/index.tsx
  packages/theme-default/src/logic/getSidebarDataGroup.ts
  packages/theme-default/src/logic/index.ts
  packages/theme-default/src/logic/usePrevNextPage.ts
Labels: change: feat

#1914 fix: display outline correctly on >=960px <=1280px screen width
  e2e/tests/hide-nav-bar.test.ts
  packages/theme-default/src/components/LocalSideBar/index.scss
  packages/theme-default/src/components/LocalSideBar/index.tsx
  packages/theme-default/src/components/Nav/index.module.scss
  packages/theme-default/src/components/NavHamburger/index.tsx
  packages/theme-default/src/components/Sidebar/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.tsx
  packages/theme-default/src/layout/Layout/index.tsx
  packages/theme-default/src/logic/utils.ts
Labels: change: fix

#1918 fix: display outline correctly on >=960px <=1280px screen width
  e2e/tests/hide-nav-bar.test.ts
  packages/theme-default/src/components/LocalSideBar/index.scss
  packages/theme-default/src/components/LocalSideBar/index.tsx
  packages/theme-default/src/components/Nav/index.module.scss
  packages/theme-default/src/components/NavHamburger/index.tsx
  packages/theme-default/src/components/Sidebar/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.tsx
  packages/theme-default/src/layout/Layout/index.tsx
  packages/theme-default/src/logic/utils.ts
Labels: change: fix

#1919 fix(plugin-api-docgen): add Russian support (#1890)
  packages/plugin-api-docgen/src/docgen.ts
  packages/plugin-api-docgen/src/index.ts
  packages/plugin-api-docgen/src/locales.ts
  packages/plugin-api-docgen/src/types.ts
Labels: change: fix

#1927 fix: remove outdated hero default values
  packages/theme-default/src/components/HomeHero/index.tsx
Labels: change: fix

#1929 fix: Revert "fix: display outline correctly on >=960px <=1280px screen width (#1914)"
  e2e/tests/hide-nav-bar.test.ts
  packages/theme-default/src/components/LocalSideBar/index.scss
  packages/theme-default/src/components/LocalSideBar/index.tsx
  packages/theme-default/src/components/Nav/index.module.scss
  packages/theme-default/src/components/NavHamburger/index.tsx
  packages/theme-default/src/components/Sidebar/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.tsx
  packages/theme-default/src/layout/Layout/index.tsx
  packages/theme-default/src/logic/utils.ts
Labels: change: fix

#1930 fix: Revert "fix: display outline correctly on >=960px <=1280px screen width (#1914)"
  e2e/tests/hide-nav-bar.test.ts
  packages/theme-default/src/components/LocalSideBar/index.scss
  packages/theme-default/src/components/LocalSideBar/index.tsx
  packages/theme-default/src/components/Nav/index.module.scss
  packages/theme-default/src/components/NavHamburger/index.tsx
  packages/theme-default/src/components/Sidebar/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.tsx
  packages/theme-default/src/layout/Layout/index.tsx
  packages/theme-default/src/logic/utils.ts
Labels: change: fix

#1934 fix: remove async fs to avoid empty global style
  packages/core/src/node/runtimeModule/globalStyles.ts
Labels: change: fix

#1928 fix: rework sidebar menu responsive issues
  e2e/tests/hide-nav-bar.test.ts
  packages/theme-default/src/components/Nav/index.module.scss
  packages/theme-default/src/components/NavHamburger/index.module.scss
  packages/theme-default/src/components/Overview/index.module.scss
  packages/theme-default/src/components/Overview/index.tsx
  packages/theme-default/src/components/Sidebar/index.module.scss
  packages/theme-default/src/components/SidebarMenu/index.scss
  packages/theme-default/src/components/SidebarMenu/index.tsx
  packages/theme-default/src/layout/DocLayout/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.tsx
  packages/theme-default/src/layout/Layout/index.tsx
  packages/theme-default/src/logic/utils.ts
  packages/theme-default/src/styles/vars.css
Labels: change: fix

#1935 fix: rework sidebar menu responsive issues
  e2e/tests/hide-nav-bar.test.ts
  packages/theme-default/src/components/LocalSideBar/index.tsx
  packages/theme-default/src/components/Nav/index.module.scss
  packages/theme-default/src/components/NavHamburger/index.module.scss
  packages/theme-default/src/components/NavHamburger/index.tsx
  packages/theme-default/src/components/Overview/index.module.scss
  packages/theme-default/src/components/Overview/index.tsx
  packages/theme-default/src/components/Sidebar/index.module.scss
  packages/theme-default/src/components/SidebarMenu/index.scss
  packages/theme-default/src/components/SidebarMenu/index.tsx
  packages/theme-default/src/layout/DocLayout/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.tsx
  packages/theme-default/src/layout/Layout/index.tsx
  packages/theme-default/src/logic/utils.ts
  packages/theme-default/src/styles/vars.css
Labels: change: fix

#1938 fix(cli): should catch build errors
  packages/cli/src/index.ts
Labels: change: fix

#1941 fix(cli): should catch build errors
  packages/cli/src/index.ts
Labels: change: fix

#1939 fix(mdxjs): not need to add base on normalizing links with base enabled
  packages/core/src/node/mdx/options.ts
  packages/core/src/node/mdx/remarkPlugins/checkDeadLink.ts
  packages/core/src/node/mdx/remarkPlugins/normalizeLink.ts
Labels: change: fix

#1943 fix(mdxjs): not need to add base on normalizing links with base enabled
  packages/core/src/node/mdx/options.ts
  packages/core/src/node/mdx/remarkPlugins/checkDeadLink.ts
  packages/core/src/node/mdx/remarkPlugins/normalizeLink.ts
Labels: change: fix

#1944 feat: expose builder preview result for programming usage
  packages/core/src/node/serve.ts
Labels: change: feat

#1945 feat: expose builder preview result for programming usage
  packages/core/src/node/serve.ts
Labels: change: feat

#1937 fix!: remove the builtin Sass and Less plugins
  e2e/fixtures/modern-js/modern.config.ts
  e2e/fixtures/modern-js/package.json
  e2e/fixtures/modern-js/src/alert.tsx
  e2e/fixtures/modern-js/src/button.tsx
  packages/core/package.json
  packages/core/src/node/initRsbuild.ts
  packages/document/docs/en/api/config/config-build.mdx
  packages/document/docs/zh/api/config/config-build.mdx
  packages/document/package.json
  packages/document/rspress.config.ts
  packages/plugin-api-docgen/static/global-components/API.css
  packages/plugin-api-docgen/static/global-components/API.scss
  packages/plugin-api-docgen/static/global-components/API.tsx
  packages/plugin-preview/static/global-components/DemoBlock.css
  packages/plugin-preview/static/global-components/DemoBlock.tsx
  packages/plugin-preview/static/global-components/Device.css
  packages/plugin-preview/static/global-components/Device.tsx
  packages/plugin-preview/static/global-components/common/index.css
  packages/plugin-preview/static/global-components/common/index.scss
  packages/plugin-preview/static/global-components/common/mobile-operation.tsx
  pnpm-lock.yaml
Labels: change: fix

#1946 fix(core): memfs should be dev dependency
  packages/core/package.json
  pnpm-lock.yaml
Labels: change: fix

#1949 fix(theme): unset overflow style when sidebar destroy
  packages/theme-default/src/components/Sidebar/index.tsx
Labels: change: fix

#1950 fix: failed to update search index after switching lang
  e2e/fixtures/search-i18n/doc/en/index.md
  e2e/fixtures/search-i18n/doc/zh/index.md
  e2e/fixtures/search-i18n/package.json
  e2e/fixtures/search-i18n/rspress.config.ts
  e2e/tests/search-i18n.test.ts
  packages/theme-default/src/components/Search/SearchPanel.tsx
  pnpm-lock.yaml
Labels: change: fix

#1909 feat(plugin-algolia): add plugin-algolia and optimize some DX on customizing Search
  e2e/fixtures/search-algolia/doc/index.mdx
  e2e/fixtures/search-algolia/package.json
  e2e/fixtures/search-algolia/rspress.config.ts
  e2e/fixtures/search-algolia/theme/index.tsx
  e2e/fixtures/search-algolia/tsconfig.json
  e2e/tests/search-algolia.test.ts
  packages/document/docs/en/plugin/official-plugins/_meta.json
  packages/document/docs/en/plugin/official-plugins/algolia.mdx
  packages/document/docs/zh/plugin/official-plugins/_meta.json
  packages/document/docs/zh/plugin/official-plugins/algolia.mdx
  packages/document/rspress.config.ts
  packages/document/theme/index.tsx
  packages/plugin-algolia/package.json
  packages/plugin-algolia/rslib.config.ts
  packages/plugin-algolia/src/index.ts
  packages/plugin-algolia/src/runtime/Search.css
  packages/plugin-algolia/src/runtime/Search.tsx
  packages/plugin-algolia/src/runtime/index.ts
  packages/plugin-algolia/src/runtime/locales.ts
  packages/runtime/src/index.ts
  packages/theme-default/src/components/Search/SearchButton.tsx
  packages/theme-default/src/components/Search/SearchPanel.tsx
  packages/theme-default/src/components/Search/index.tsx
  packages/theme-default/src/components/SwitchAppearance/index.tsx
  packages/theme-default/src/index.ts
  playwright.config.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
Labels: change: feat

#1951 fix(deps): update react-helmet-async 2.0.0
  packages/core/rslib.config.ts
Labels: change: fix

#1952 feat: enable `search.codeBlocks` by default
  e2e/fixtures/search-code-blocks/rspress.config.ts
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
Labels: change: feat

#1953 fix(deps): update react-helmet-async 2.0.0(#1951)
  .github/workflows/test-Windows.yml
  .github/workflows/test-macOS.yml
  packages/core/rslib.config.ts
  packages/core/src/node/build.ts
Labels: change: fix

#1956 fix: improve reported responsive issues
  packages/plugin-preview/static/global-styles/iframe.css
  packages/theme-default/src/components/Nav/index.module.scss
  packages/theme-default/src/components/Nav/index.tsx
  packages/theme-default/src/components/SidebarMenu/index.scss
  packages/theme-default/src/components/SidebarMenu/index.tsx
  packages/theme-default/src/layout/DocLayout/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.tsx
Labels: change: fix

#1958 docs: update i18n messages
  packages/document/i18n.json
  packages/document/rspress.config.ts
Labels: change: docs

#1960 fix: overview page overflow
  packages/theme-default/src/layout/DocLayout/index.tsx
Labels: change: fix

#1961 fix: improve reported responsive issues
  packages/plugin-preview/static/global-styles/iframe.css
  packages/theme-default/src/components/Nav/index.module.scss
  packages/theme-default/src/components/Nav/index.tsx
  packages/theme-default/src/components/Sidebar/index.tsx
  packages/theme-default/src/components/SidebarMenu/index.scss
  packages/theme-default/src/components/SidebarMenu/index.tsx
  packages/theme-default/src/layout/DocLayout/index.module.scss
  packages/theme-default/src/layout/DocLayout/index.tsx
Labels: change: fix

#1964 feat(style): add link icon for external links
  packages/theme-default/src/layout/DocLayout/docComponents/index.module.scss
Labels: change: feat

#1965 fix: update search placeholder text to 'Search'
  packages/document/docs/en/api/config/config-theme.mdx
  packages/document/docs/zh/api/config/config-theme.mdx
  packages/document/rspress.config.ts
  packages/theme-default/src/components/Search/SearchButton.tsx
  packages/theme-default/src/components/Search/SearchPanel.tsx
Labels: change: fix

#1969 docs: add `editLink` and `outline` config
  packages/document/docs/en/api/config/config-theme.mdx
  packages/document/docs/zh/api/config/config-theme.mdx
Labels: change: docs

#1978 fix(theme/PrevNextPage): should be hidden when text is undefined or `""`
  packages/theme-default/src/components/DocFooter/index.tsx
  packages/theme-default/src/logic/usePrevNextPage.ts
Labels: change: fix

#1980 fix: normalize jsx img src attribute correctly
  packages/core/package.json
  packages/core/src/node/mdx/options.ts
  packages/core/src/node/mdx/remarkPlugins/normalizeLink.ts
  packages/core/tests/__snapshots__/md.test.ts.snap
  packages/core/tests/md.test.ts
  packages/shared/src/node-utils/getNodeAttribute.ts
  pnpm-lock.yaml
Labels: change: fix

#1979 fix: normalize jsx img src attribute correctly
  packages/core/package.json
  packages/core/src/node/mdx/options.ts
  packages/core/src/node/mdx/remarkPlugins/normalizeLink.ts
  packages/core/tests/__snapshots__/md.test.ts.snap
  packages/core/tests/md.test.ts
  packages/shared/src/node-utils/getNodeAttribute.ts
  pnpm-lock.yaml
Labels: change: fix

#1984 fix: continue work on responsive styling issues
  packages/theme-default/src/components/Aside/index.tsx
  packages/theme-default/src/components/Nav/index.module.scss
  packages/theme-default/src/components/Overview/index.module.scss
  packages/theme-default/src/components/SidebarMenu/index.scss
  packages/theme-default/src/components/SidebarMenu/index.tsx
  packages/theme-default/src/components/Toc/index.tsx
  packages/theme-default/src/layout/DocLayout/index.tsx
  pnpm-lock.yaml
Labels: change: fix

#1987 docs: enhance front matter documentation
  packages/document/docs/en/api/config/config-frontmatter.mdx
  packages/document/docs/en/guide/basic/use-mdx.mdx
  packages/document/docs/zh/api/config/config-frontmatter.mdx
  packages/document/docs/zh/guide/basic/use-mdx.mdx
Labels: change: docs

#1991 docs: format command bash space
  packages/document/docs/en/api/commands.mdx
  packages/document/docs/zh/api/commands.mdx
Labels: change: docs

#1988 fix(mdxjs): add `version` and `lang` part when normalizing links
  packages/core/src/node/mdx/options.ts
  packages/core/src/node/mdx/remarkPlugins/checkDeadLink.ts
  packages/core/src/node/mdx/remarkPlugins/normalizeLink.ts
  packages/core/src/node/route/RouteService.ts
  packages/core/src/node/route/normalizeRoutePath.test.ts
  packages/core/src/node/route/normalizeRoutePath.ts
Labels: change: fix

#1998 fix(mdxjs): add `version` and `lang` part when normalizing links
  packages/core/src/node/mdx/options.ts
  packages/core/src/node/mdx/remarkPlugins/checkDeadLink.ts
  packages/core/src/node/mdx/remarkPlugins/normalizeLink.ts
  packages/core/src/node/route/RouteService.ts
  packages/core/src/node/route/normalizeRoutePath.test.ts
  packages/core/src/node/route/normalizeRoutePath.ts
Labels: change: fix

#1990 feat(theme)!: add prefix for isolating tailwind css
  packages/core/src/node/constants.ts
  packages/theme-default/src/components/Aside/index.tsx
  packages/theme-default/src/components/Badge/index.tsx
  packages/theme-default/src/components/Card/index.tsx
  packages/theme-default/src/components/DocFooter/index.tsx
  packages/theme-default/src/components/HomeFeature/index.tsx
  packages/theme-default/src/components/HomeFooter/index.tsx
  packages/theme-default/src/components/HomeHero/index.tsx
  packages/theme-default/src/components/LastUpdated/index.tsx
  packages/theme-default/src/components/LinkCard/index.tsx
  packages/theme-default/src/components/Nav/NavBarTitle.tsx
  packages/theme-default/src/components/Nav/NavMenuGroup.tsx
  packages/theme-default/src/components/Nav/NavMenuSingleItem.tsx
  packages/theme-default/src/components/Nav/NavTranslations.tsx
  packages/theme-default/src/components/Nav/NavVersions.tsx
  packages/theme-default/src/components/Nav/index.tsx
  packages/theme-default/src/components/NavScreen/NavScreenMenuGroup.tsx
  packages/theme-default/src/components/NavScreen/index.tsx
  packages/theme-default/src/components/Overview/index.tsx
  packages/theme-default/src/components/ScrollToTop/index.tsx
  packages/theme-default/src/components/Search/NoSearchResult.tsx
  packages/theme-default/src/components/Search/SuggestItem.tsx
  packages/theme-default/src/components/Sidebar/SidebarDivider.tsx
  packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
  packages/theme-default/src/components/Sidebar/SidebarItem.tsx
  packages/theme-default/src/components/Sidebar/index.tsx
  packages/theme-default/src/components/SidebarMenu/index.tsx
  packages/theme-default/src/components/SocialLinks/HiddenLinks.tsx
  packages/theme-default/src/components/SocialLinks/LinkContent.tsx
  packages/theme-default/src/components/SocialLinks/ShownLinks.tsx
  packages/theme-default/src/components/SocialLinks/index.tsx
  packages/theme-default/src/components/SourceCode/index.tsx
  packages/theme-default/src/components/Steps/index.tsx
  packages/theme-default/src/components/SwitchAppearance/index.tsx
  packages/theme-default/src/components/Tabs/index.tsx
  packages/theme-default/src/components/Toc/index.tsx
  packages/theme-default/src/layout/DocLayout/docComponents/hr.tsx
  packages/theme-default/src/layout/DocLayout/docComponents/list.tsx
  packages/theme-default/src/layout/DocLayout/docComponents/paragraph.tsx
  packages/theme-default/src/layout/DocLayout/docComponents/table.tsx
  packages/theme-default/src/layout/DocLayout/docComponents/title.tsx
  packages/theme-default/src/layout/DocLayout/index.tsx
  packages/theme-default/src/layout/HomeLayout/index.tsx
  packages/theme-default/src/layout/NotFountLayout/index.tsx
  packages/theme-default/src/logic/useAppearance.ts
  packages/theme-default/src/styles/base.css
  packages/theme-default/tailwind.config.ts
Labels: change: feat

#2004 fix(plugin-api-docgen): fallback to en, and should report warning msg when no replacing
  packages/plugin-api-docgen/src/index.ts
Labels: change: fix

#2008 fix(theme/style): SearchPanel is not styled by tailwind
  packages/theme-default/src/components/HomeHero/index.tsx
  packages/theme-default/src/components/NavHamburger/index.tsx
  packages/theme-default/src/components/Search/SearchPanel.tsx
Labels: change: fix

#2012 fix(cli): polish theme namedExport breaking change hint
  packages/core/src/node/logger/hint.ts
  packages/core/tests/cli/hint.test.ts
Labels: change: fix

#2015 feat(config)!: force successful SSG generation, remove `ssg.strict` and add `ssg.fallback`
  e2e/fixtures/ssg-fail-strict/rspress.config.ts
  packages/core/src/node/build.ts
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/document/rspress.config.ts
  packages/shared/src/types/index.ts
Labels: change: feat
