Repository web-infra-dev/rspress, pull requests merged in 2025-07, with the labels that each got.

#2345 fix(theme/dynamic-toc): remove comment for props replacing in SSG
  packages/theme-default/src/components/Aside/processTitleElement.ts
Labels: change: fix

#2348 fix(remarkNormalizeLink)!: support relative path [subfolder](subfolder) which is equal to [subfolder](./subfolder)
  e2e/fixtures/check-dead-link/doc/en/guide/basic/quick-start.mdx
  e2e/fixtures/check-dead-link/doc/zh/guide/basic/quick-start.mdx
  e2e/fixtures/check-dead-link/index.test.ts
  e2e/fixtures/markdown-link/doc/guide/index.mdx
  e2e/fixtures/markdown-link/index.test.ts
  e2e/fixtures/markdown-link/rspress.config.ts
  packages/core/src/node/mdx/remarkPlugins/normalizeLink.ts
  packages/core/src/node/route/RouteService.test.ts
  packages/core/src/node/route/fixtures/locales/en/guide/basic/install.mdx
  packages/core/src/node/route/fixtures/locales/en/guide/basic/quick-start.mdx
  packages/core/src/node/route/fixtures/locales/en/guide/index.mdx
  packages/core/src/node/route/fixtures/locales/en/index.mdx
  packages/core/src/node/route/fixtures/locales/zh/guide/basic/install.mdx
  packages/core/src/node/route/fixtures/locales/zh/guide/basic/quick-start.mdx
  packages/core/src/node/route/fixtures/locales/zh/guide/index.mdx
  packages/core/src/node/route/fixtures/locales/zh/index.mdx
  packages/core/src/node/route/normalizeRoutePath.ts
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
Labels: change: fix

#2347 feat(plugin-llms): multiple configuration for multiple llms.txt
  e2e/fixtures/plugin-llms/doc-i18n/en/_nav.json
  e2e/fixtures/plugin-llms/doc-i18n/en/api/index.mdx
  e2e/fixtures/plugin-llms/doc-i18n/en/guide/_meta.json
  e2e/fixtures/plugin-llms/doc-i18n/en/guide/basic/install.mdx
  e2e/fixtures/plugin-llms/doc-i18n/en/guide/basic/quick-start.mdx
  e2e/fixtures/plugin-llms/doc-i18n/en/index.md
  e2e/fixtures/plugin-llms/doc-i18n/zh/_nav.json
  e2e/fixtures/plugin-llms/doc-i18n/zh/api/index.mdx
  e2e/fixtures/plugin-llms/doc-i18n/zh/guide/_meta.json
  e2e/fixtures/plugin-llms/doc-i18n/zh/guide/basic/install.mdx
  e2e/fixtures/plugin-llms/doc-i18n/zh/guide/basic/quick-start.mdx
  e2e/fixtures/plugin-llms/doc-i18n/zh/index.md
  e2e/fixtures/plugin-llms/index.test.ts
  e2e/fixtures/plugin-llms/rspress-i18n.config.ts
  packages/document/docs/en/plugin/official-plugins/llms.mdx
  packages/document/docs/zh/plugin/official-plugins/llms.mdx
  packages/document/rspress.config.ts
  packages/plugin-llms/src/llmsTxt.ts
  packages/plugin-llms/src/plugin.ts
  packages/plugin-llms/src/types.ts
Labels: change: feat

#2349 feat(rsbuild)!: enable persistent cache by default via `performance.buildCache`
  packages/cli/src/config/loadConfigFile.ts
  packages/cli/src/index.ts
  packages/cli/tests/config/config-basic.test.ts
  packages/core/src/node/PluginDriver.ts
  packages/core/src/node/build.ts
  packages/core/src/node/dev.ts
  packages/core/src/node/initRsbuild.ts
  packages/core/src/node/route/RouteService.test.ts
  packages/core/src/node/serve.ts
Labels: change: feat

#2356 fix(plugin-typedoc): skip patch raw links
  e2e/fixtures/plugin-typedoc/index.test.ts
  e2e/fixtures/plugin-typedoc/multi/rspress.config.ts
  e2e/fixtures/plugin-typedoc/multi/src/raw-link.ts
  packages/plugin-typedoc/src/patch.ts
Labels: change: fix

#2365 docs: update PackageManagerTabs tips for pnpm
  packages/document/docs/en/fragments/builtin-components.mdx
Labels: change: docs

#2373 fix: use `withBase` from runtime
  packages/theme-default/src/components/HomeFeature/index.tsx
  packages/theme-default/src/components/HomeHero/index.tsx
Labels: change: fix

#2378 fix(buildCache): other configuration files besides `rspress.config.ts` should be added to persistent cache deps
  packages/cli/src/index.ts
  packages/core/src/node/initRsbuild.ts
Labels: change: fix

#2394 perf(ssg): add `ssg.experimentalWorker` based on tinypool to speed up ssg process
  packages/core/package.json
  packages/core/rslib.config.ts
  packages/core/src/node/build.ts
  packages/core/src/node/initRsbuild.ts
  packages/core/src/node/runtimeModule/runtimeConfig.ts
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/core/src/node/ssg/renderHtmlTemplate.ts
  packages/core/src/node/ssg/renderPage.ts
  packages/core/src/node/ssg/renderPageWorker.ts
  packages/core/src/node/ssg/renderPages.ts
  packages/core/src/node/ssg/rsbuildPluginCSR.ts
  packages/core/src/node/ssg/rsbuildPluginSSG.ts
  packages/core/src/runtime/env.d.ts
  packages/core/src/runtime/ssrServerEntry.tsx
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/document/rspress.config.ts
  packages/shared/src/types/index.ts
  pnpm-lock.yaml
Labels: change: perf

#2401 fix(theme): aside should not cover the top buttons (#2400)
  packages/theme-default/src/layout/DocLayout/index.module.scss
Labels: change: fix

#2405 feat(ssg): add `ssg.experimentalExcludeRoutePaths`
  packages/core/src/node/runtimeModule/runtimeConfig.ts
  packages/core/src/node/ssg/renderPages.ts
  packages/core/src/node/ssg/ssgEnv.ts
  packages/core/src/runtime/ssrServerEntry.tsx
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/document/rspress.config.ts
  packages/shared/src/types/defaultTheme.ts
  packages/shared/src/types/index.ts
Labels: change: feat

#2149 feat(core)!: routeService ignore "_" prefix files by default
  packages/core/src/node/route/RouteService.test.ts
  packages/core/src/node/route/RouteService.ts
  packages/core/src/node/route/fixtures/basic/guide/__e.mdx
  packages/core/src/node/route/fixtures/basic/guide/_d.mdx
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/en/guide/basic/use-mdx/_Border.tsx
  packages/document/docs/en/guide/basic/use-mdx/_button.mdx
  packages/document/docs/en/guide/basic/use-mdx/_escape-hatch.tsx
  packages/document/docs/en/guide/basic/use-mdx/_mdx-fragment.mdx
  packages/document/docs/en/guide/basic/use-mdx/_meta.json
  packages/document/docs/en/guide/basic/use-mdx/_tsx-component.tsx
  packages/document/docs/en/guide/basic/use-mdx/components.mdx
  packages/document/docs/env.d.ts
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/document/docs/zh/guide/basic/use-mdx/_Border.tsx
  packages/document/docs/zh/guide/basic/use-mdx/_button.mdx
  packages/document/docs/zh/guide/basic/use-mdx/_escape-hatch.tsx
  packages/document/docs/zh/guide/basic/use-mdx/_mdx-fragment.mdx
  packages/document/docs/zh/guide/basic/use-mdx/_meta.json
  packages/document/docs/zh/guide/basic/use-mdx/_tsx-component.tsx
  packages/document/docs/zh/guide/basic/use-mdx/components.mdx
  packages/document/docs/zh/guide/basic/use-mdx/index.mdx
  packages/document/rspress.config.ts
  packages/shared/src/types/index.ts
Labels: change: feat

#2423 fix(fileCodeBlock): should support hmr
  packages/core/src/node/mdx/loader.ts
  packages/core/src/node/mdx/options.ts
  packages/core/src/node/mdx/processor.ts
  packages/core/src/node/mdx/remarkPlugins/fileCodeBlock.ts
Labels: change: fix
