Repository web-infra-dev/rspress, pull requests merged in 2025-04, with the labels that each got.

#2028 fix(plugin-playground): disable monaco editor ts check for supporting tsx
  packages/plugin-playground/static/global-components/Playground.tsx
Labels: change: fix

#2044 fix(plugin-container): incorrect trimming in some cases
  packages/plugin-container-syntax/src/remarkPlugin.ts
  packages/plugin-container-syntax/tests/__snapshots__/index.test.ts.snap
  packages/plugin-container-syntax/tests/index.test.ts
Labels: change: fix

#2042 feat(plugin-shiki): improve line diff colors
  packages/plugin-shiki/shiki.css
Labels: change: feat

#2047 fix(firefox): location too much change firefox issue
  packages/theme-default/src/logic/useUISwitch.ts
Labels: change: fix

#2049 fix(plugin-container): avoid unexpected line breaks
  packages/plugin-container-syntax/src/remarkPlugin.ts
  packages/plugin-container-syntax/tests/__snapshots__/index.test.ts.snap
  packages/plugin-container-syntax/tests/index.test.ts
Labels: change: fix

#2050 fix(plugin-shiki): no code title
  e2e/fixtures/plugin-shiki/doc/index.mdx
  e2e/tests/plugin-shiki.test.ts
  packages/document/package.json
  packages/document/rspress.config.ts
  packages/plugin-shiki/src/shiki/pluginShiki.ts
  packages/plugin-shiki/src/shiki/transformers/add-title.ts
  packages/theme-default/src/layout/DocLayout/docComponents/pre.tsx
  pnpm-lock.yaml
Labels: change: fix

#2056 fix(firefox): location too much change firefox issue #2047
  packages/theme-default/src/logic/useUISwitch.ts
Labels: change: fix

#2057 feat(theme-default): add beforeHeroActions and afterHeroActions
  packages/theme-default/src/components/HomeHero/index.tsx
  packages/theme-default/src/index.ts
  packages/theme-default/src/layout/HomeLayout/index.tsx
Labels: change: feat

#2063 fix: wrong hydration, hydrate twice
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/core/src/runtime/ClientApp.tsx
  packages/core/src/runtime/clientEntry.tsx
Labels: change: fix

#2043 feat: plugin preview add custom entry option
  e2e/fixtures/plugin-preview-custom-entry/doc/index.mdx
  e2e/fixtures/plugin-preview-custom-entry/package.json
  e2e/fixtures/plugin-preview-custom-entry/rspress.config.ts
  e2e/fixtures/plugin-preview-custom-entry/tsconfig.json
  e2e/tests/plugin-preview-custom-entry.test.ts
  packages/document/docs/en/plugin/official-plugins/preview.mdx
  packages/document/docs/zh/plugin/official-plugins/preview.mdx
  packages/plugin-preview/src/generate-entry.ts
  packages/plugin-preview/src/index.ts
  packages/plugin-preview/src/remarkPlugin.ts
  packages/plugin-preview/src/types.ts
  packages/plugin-preview/src/utils.ts
  pnpm-lock.yaml
Labels: change: feat

#2071 docs: correct meta tags generation example
  packages/document/docs/en/api/config/config-frontmatter.mdx
  packages/document/docs/en/guide/basic/custom-page.mdx
  packages/document/docs/zh/api/config/config-frontmatter.mdx
  packages/document/docs/zh/guide/basic/custom-page.mdx
Labels: change: docs

#2077 docs: migrate to docsearch new account
  packages/document/rspress.config.ts
Labels: change: docs

#2083 fix: remove useless peerDependencies and pin react-router-dom version
  packages/core/package.json
  packages/core/src/node/initRsbuild.ts
  packages/core/src/node/utils/detectReactVersion.ts
  packages/plugin-api-docgen/package.json
  packages/plugin-playground/package.json
  packages/plugin-playground/src/cli/index.ts
  packages/plugin-preview/package.json
  packages/plugin-rss/package.json
  pnpm-lock.yaml
Labels: change: fix

#2084 feat: migrate all the packages to "type: module" and pure esm with publint
  packages/cli/package.json
  packages/cli/rslib.config.ts
  packages/core/package.json
  packages/core/rslib.config.ts
  packages/create-rspress/package.json
  packages/create-rspress/rslib.config.ts
  packages/document/package.json
  packages/plugin-algolia/package.json
  packages/plugin-algolia/rslib.config.ts
  packages/plugin-api-docgen/mdx-meta-loader.cjs
  packages/plugin-api-docgen/package.json
  packages/plugin-api-docgen/rslib.config.ts
  packages/plugin-auto-nav-sidebar/package.json
  packages/plugin-auto-nav-sidebar/rslib.config.ts
  packages/plugin-client-redirects/package.json
  packages/plugin-client-redirects/rslib.config.ts
  packages/plugin-container-syntax/package.json
  packages/plugin-container-syntax/rslib.config.ts
  packages/plugin-last-updated/package.json
  packages/plugin-last-updated/rslib.config.ts
  packages/plugin-medium-zoom/package.json
  packages/plugin-medium-zoom/rslib.config.ts
  packages/plugin-playground/package.json
  packages/plugin-playground/rslib.config.ts
  packages/plugin-playground/src/cli/constant.ts
  packages/plugin-playground/src/cli/index.ts
  packages/plugin-playground/static/global-components/Playground.tsx
  packages/plugin-preview/package.json
  packages/plugin-preview/rslib.config.ts
  packages/plugin-rss/package.json
  packages/plugin-rss/rslib.config.ts
  packages/plugin-shiki/package.json
  packages/plugin-shiki/rslib.config.ts
  packages/plugin-typedoc/package.json
  packages/plugin-typedoc/rslib.config.ts
  packages/runtime/package.json
  packages/runtime/rslib.config.ts
  packages/shared/package.json
  packages/shared/rslib.config.ts
  packages/theme-default/package.json
  packages/theme-default/rslib.config.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
Labels: change: feat

#2086 fix: reduce react-router-dom bundle size
  packages/core/src/node/initRsbuild.ts
  packages/core/src/node/utils/detectReactVersion.ts
Labels: change: fix

#2088 fix(style): change flex to rp-flex
  packages/plugin-preview/static/global-components/Container.tsx
Labels: change: fix

#2034 feat(plugin-llms): init @rspress/plugin-llms
  packages/core/package.json
  packages/core/src/index.ts
  packages/core/src/node/PluginDriver.ts
  packages/core/src/node/index.ts
  packages/core/src/node/mdx/remarkPlugins/normalizeLink.ts
  packages/core/src/node/route/init.ts
  packages/core/src/node/runtimeModule/siteData/extractPageData.test.ts
  packages/core/src/node/runtimeModule/siteData/extractPageData.ts
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/core/tests/prismLanguages.test.ts
  packages/document/docs/en/plugin/official-plugins/_meta.json
  packages/document/docs/en/plugin/official-plugins/llms.mdx
  packages/document/docs/en/plugin/official-plugins/overview.mdx
  packages/document/docs/zh/_meta.json
  packages/document/docs/zh/plugin/official-plugins/_meta.json
  packages/document/docs/zh/plugin/official-plugins/llms.mdx
  packages/document/docs/zh/plugin/official-plugins/overview.mdx
  packages/document/i18n.json
  packages/document/package.json
  packages/document/rspress.config.ts
  packages/plugin-llms/LICENSE
  packages/plugin-llms/README.md
  packages/plugin-llms/package.json
  packages/plugin-llms/rslib.config.ts
  packages/plugin-llms/src/env.d.ts
  packages/plugin-llms/src/index.ts
  packages/plugin-llms/src/llmsTxt.ts
  packages/plugin-llms/src/mdxToMd.ts
  packages/plugin-llms/src/plugin.ts
  packages/plugin-llms/src/types.ts
  packages/plugin-llms/tests/tsconfig.json
  packages/plugin-llms/tsconfig.json
  packages/runtime/server.d.ts
  packages/runtime/server.js
  packages/runtime/src/index.ts
  packages/shared/src/index.ts
  packages/shared/src/runtime-utils/navbar.ts
  packages/shared/src/runtime-utils/sidebar.ts
  packages/shared/src/runtime-utils/utils.test.ts
  packages/shared/src/runtime-utils/utils.ts
  packages/shared/src/types/Plugin.ts
  packages/shared/src/types/index.ts
  packages/theme-default/src/components/Nav/NavMenuGroup.tsx
  packages/theme-default/src/logic/getSidebarDataGroup.ts
  pnpm-lock.yaml
  scripts/dictionary.txt
Labels: change: feat

#2093 feat(plugin-llms): add include option and only generate for default lang
  packages/document/docs/en/plugin/official-plugins/llms.mdx
  packages/document/docs/zh/plugin/official-plugins/llms.mdx
  packages/plugin-llms/src/plugin.ts
  packages/plugin-llms/src/types.ts
Labels: change: feat

#2097 fix(plugin-api-docgen): fallback to en, and should report warning msg when no replacing (#2004)
  packages/plugin-api-docgen/src/index.ts
Labels: change: fix

#2100 fix: the nav bar lowerCase
  packages/document/docs/en/_meta.json
Labels: change: fix

#2099 docs: add v2 website link to v1 website
  packages/document/docs/en/_meta.json
  packages/document/docs/zh/_meta.json
Labels: change: docs

#2108 docs: add 1.x doc link
  packages/document/docs/en/_meta.json
  packages/document/docs/zh/_meta.json
Labels: change: docs

#2018 feat(theme/toc)!: use dynamic toc generation
  e2e/tests/inline-markdown.test.ts
  packages/theme-default/src/components/Aside/index.tsx
  packages/theme-default/src/components/Aside/useDynamicToc.ts
  packages/theme-default/src/components/SidebarMenu/index.tsx
  packages/theme-default/src/components/Toc/index.tsx
  packages/theme-default/src/index.ts
  packages/theme-default/src/layout/DocLayout/docComponents/title.tsx
  packages/theme-default/src/layout/DocLayout/index.tsx
Labels: change: feat
