Repository web-infra-dev/rspress, pull requests merged in 2025-05, with the labels that each got.

#2116 fix(plugin-llms): group routes correctly without locales config
  packages/plugin-llms/src/plugin.ts
Labels: change: fix

#2119 fix(theme/dynamic-toc): should abandon all elements with `display: none`.
  packages/theme-default/src/components/Aside/index.tsx
  packages/theme-default/src/components/Aside/useDynamicToc.ts
Labels: change: fix

#2127 fix: the pkg type error in moduleResolution: node16
  packages/core/package.json
  packages/core/rslib.config.ts
  packages/plugin-algolia/rslib.config.ts
  packages/runtime/rslib.config.ts
  packages/theme-default/.theme-entry.d.ts
  packages/theme-default/.theme-entry.js
  pnpm-lock.yaml
Labels: change: fix

#2125 feat: add `localeRedirect: 'only-default-lang'` support
  packages/document/docs/en/api/config/config-theme.mdx
  packages/document/docs/zh/api/config/config-theme.mdx
  packages/shared/src/types/defaultTheme.ts
  packages/theme-default/src/logic/useRedirect4FirstVisit.ts
Labels: change: feat

#2129 feat: add `localeRedirect: 'only-default-lang'` support
  packages/document/docs/en/api/config/config-theme.mdx
  packages/document/docs/zh/api/config/config-theme.mdx
  packages/shared/src/types/defaultTheme.ts
  packages/theme-default/src/logic/useRedirect4FirstVisit.ts
Labels: change: feat

#2123 feat!: enable `dev.lazyCompilation: true` by default
  e2e/utils/runCommands.ts
  packages/core/src/node/initRsbuild.ts
Labels: change: feat

#2128 feat: upgrade create-rspress to support `npm create rspress@beta`
  packages/create-rspress/template-basic/package.json
  packages/document/theme/index.tsx
  packages/theme-default/src/layout/DocLayout/docComponents/code/CodeButtonGroup.tsx
  packages/theme-default/src/layout/DocLayout/docComponents/code/CopyCodeButton.tsx
  packages/theme-default/src/layout/DocLayout/docComponents/code/index.tsx
  packages/theme-default/src/layout/DocLayout/docComponents/pre.tsx
Labels: change: feat

#2131 docs(algolia-search): use new docsearch account and optimize the dark mode
  packages/document/rspress.config.ts
  packages/document/theme/index.tsx
  packages/plugin-algolia/src/runtime/Search.css
  packages/runtime/src/hooks.ts
  packages/theme-default/src/components/Nav/index.module.scss
  packages/theme-default/src/components/Nav/index.tsx
Labels: change: docs

#2079 feat: add `_meta.json` json schema in `rspress/meta-json-schema.json`
  .gitignore
  .prettierignore
  .vscode/settings.json
  biome.json
  packages/cli/package.json
  packages/cli/scripts/generateJsonSchema.mjs
  packages/plugin-auto-nav-sidebar/src/type.ts
  packages/plugin-auto-nav-sidebar/src/walk.ts
  pnpm-lock.yaml
Labels: change: feat

#2134 fix(theme/dynamic-toc): skip <a /> element in TOC
  packages/theme-default/src/components/Aside/processTitleElement.ts
  packages/theme-default/src/components/Aside/useDynamicToc.ts
Labels: change: fix

#2136 feat(theme/dynamic-toc): add .rspress-toc-exclude escape hatch
  packages/theme-default/src/components/Aside/processTitleElement.ts
Labels: change: feat

#2138 fix(deps): remove unused react-syntax-highlighter
  packages/core/package.json
  packages/core/src/node/initRsbuild.ts
  packages/theme-default/package.json
  pnpm-lock.yaml
Labels: change: fix

#2140 fix(plugin-api-doc-gen): plugin-api-doc-gen should have anchor
  e2e/tests/plugin-api-docgen.test.ts
  packages/plugin-api-docgen/package.json
  packages/plugin-api-docgen/static/global-components/API.tsx
  pnpm-lock.yaml
Labels: change: fix

#2141 feat: update Rsbuild 1.3.18 and set caller name
  packages/cli/package.json
  packages/core/package.json
  packages/core/src/node/initRsbuild.ts
  packages/create-rspress/package.json
  packages/modern-plugin-rspress/package.json
  packages/plugin-api-docgen/package.json
  packages/plugin-auto-nav-sidebar/package.json
  packages/plugin-client-redirects/package.json
  packages/plugin-container-syntax/package.json
  packages/plugin-last-updated/package.json
  packages/plugin-medium-zoom/package.json
  packages/plugin-playground/package.json
  packages/plugin-preview/package.json
  packages/plugin-preview/src/index.ts
  packages/plugin-rss/package.json
  packages/plugin-shiki/package.json
  packages/plugin-typedoc/package.json
  packages/runtime/package.json
  packages/shared/package.json
  packages/theme-default/package.json
  pnpm-lock.yaml
Labels: change: feat

#2146 fix(plugin-api-doc-gen): plugin-api-doc-gen should have anchor (#2140)
  e2e/tests/plugin-api-docgen.test.ts
  packages/plugin-api-docgen/package.json
  packages/plugin-api-docgen/static/global-components/API.tsx
  pnpm-lock.yaml
Labels: change: fix

#2147 fix(plugin-playground): disable monaco editor ts check for supporting tsx #2028
  e2e/fixtures/plugin-playground/doc/index.mdx
  e2e/tests/plugin-playground.test.ts
  packages/document/docs/en/plugin/official-plugins/playground.mdx
  packages/document/docs/zh/plugin/official-plugins/playground.mdx
  packages/plugin-playground/static/global-components/Playground.tsx
Labels: change: fix

#2150 docs: replace `Helmet` with `Head`
  packages/document/docs/en/api/config/config-frontmatter.mdx
  packages/document/docs/en/fragments/builtin-components.mdx
  packages/document/docs/zh/api/config/config-frontmatter.mdx
  packages/document/docs/zh/fragments/builtin-components.mdx
Labels: change: docs

#2152 feat(plugin-preview): add iframePostion 'fixed-with-per-comp'
  e2e/tests/modern-js.test.ts
  packages/document/docs/en/plugin/official-plugins/preview.mdx
  packages/document/docs/zh/plugin/official-plugins/preview.mdx
  packages/plugin-preview/src/generate-entry.ts
  packages/plugin-preview/src/index.ts
  packages/plugin-preview/src/remarkPlugin.ts
  packages/plugin-preview/src/types.ts
  packages/plugin-preview/static/global-components/Container.tsx
  packages/plugin-preview/static/global-components/ContainerFixedPerComp.tsx
  packages/plugin-preview/static/global-components/Device.scss
  packages/plugin-preview/static/global-components/Device.tsx
  packages/plugin-preview/static/global-components/common/index.scss
Labels: change: feat

#2153 fix(theme): highlight the <PackageManagerTabs /> manually
  e2e/tests/package-manager-tabs.test.ts
  packages/theme-default/src/components/PackageManagerTabs/index.tsx
Labels: change: fix

#2157 docs: update website contributing guide
  packages/document/README.md
Labels: change: docs

#2161 feat(theme): expose classname for crawler
  packages/theme-default/src/components/Nav/NavMenuSingleItem.tsx
  packages/theme-default/src/components/Sidebar/SidebarItem.tsx
Labels: change: feat

#2163 docs(algolia): update index name
  packages/document/theme/index.tsx
Labels: change: docs

#2164 feat(core): support md definition syntax url
  e2e/fixtures/markdown-link/doc/_meta.json
  e2e/fixtures/markdown-link/doc/guide/index.mdx
  e2e/fixtures/markdown-link/doc/guide/installation.mdx
  e2e/fixtures/markdown-link/doc/guide/subfolder/foo.mdx
  e2e/fixtures/markdown-link/doc/guide/subfolder/index.mdx
  e2e/fixtures/markdown-link/doc/index.md
  e2e/fixtures/markdown-link/package.json
  e2e/fixtures/markdown-link/rspress.config.ts
  e2e/fixtures/markdown-link/tsconfig.json
  e2e/fixtures/nav-link/doc/_meta.json
  e2e/fixtures/nav-link/doc/index.md
  e2e/fixtures/nav-link/package.json
  e2e/fixtures/nav-link/rspress.config.ts
  e2e/fixtures/nav-link/tsconfig.json
  e2e/tests/markdown-link.test.ts
  e2e/tests/nav-link.test.ts
  packages/core/src/node/mdx/remarkPlugins/checkDeadLink.ts
  packages/core/src/node/mdx/remarkPlugins/normalizeLink.ts
  pnpm-lock.yaml
Labels: change: feat

#2169 docs: add Rstest to homepage
  packages/document/i18n.json
  packages/document/package.json
  packages/document/theme/components/ToolStack.tsx
  pnpm-lock.yaml
Labels: change: docs

#2167 feat: support `file://` protocol and `URL` for icon
  e2e/fixtures/icon-file-url/docs/index.md
  e2e/fixtures/icon-file-url/package.json
  e2e/fixtures/icon-file-url/rspress.config.ts
  e2e/fixtures/icon-file-url/tsconfig.json
  e2e/tests/icon-file-url.test.ts
  packages/core/src/node/initRsbuild.ts
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/en/guide/basic/static-assets.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/document/docs/zh/guide/basic/static-assets.mdx
  packages/plugin-rss/src/plugin-rss.ts
  packages/shared/src/node-utils.ts
  packages/shared/src/node-utils/getIconUrlPath.ts
  packages/shared/src/types/index.ts
  pnpm-lock.yaml
Labels: change: feat

#2168 fix(core/mdx-loader): due to frontmatter stack error loc and remove useless hmr old codes
  packages/core/src/node/mdx/loader.ts
  packages/shared/src/node-utils/loadFrontMatter.ts
Labels: change: fix

#2170 feat: support `file://` protocol and `URL` for icon
  e2e/fixtures/icon-file-url/docs/index.md
  e2e/fixtures/icon-file-url/package.json
  e2e/fixtures/icon-file-url/rspress.config.ts
  e2e/fixtures/icon-file-url/tsconfig.json
  e2e/tests/icon-file-url.test.ts
  packages/core/src/node/initRsbuild.ts
  packages/core/src/node/runtimeModule/siteData/index.ts
  packages/document/docs/en/api/config/config-basic.mdx
  packages/document/docs/en/guide/basic/static-assets.mdx
  packages/document/docs/zh/api/config/config-basic.mdx
  packages/document/docs/zh/guide/basic/static-assets.mdx
  packages/plugin-rss/src/plugin-rss.ts
  packages/shared/src/node-utils.ts
  packages/shared/src/node-utils/getIconUrlPath.ts
  packages/shared/src/types/index.ts
  pnpm-lock.yaml
Labels: change: feat

#2171 fix(core/mdx-loader): due to frontmatter stack error loc and remove useless hmr old codes (#2168)
  packages/core/src/node/mdx/loader.ts
  packages/shared/src/node-utils/loadFrontMatter.ts
Labels: change: fix

#2175 fix(shiki/css): add diff language token and remove useless prism token
  e2e/fixtures/plugin-shiki/doc/index.mdx
  e2e/tests/plugin-shiki.test.ts
  packages/plugin-algolia/src/runtime/Search.css
  packages/plugin-shiki/src/shiki.scss
  packages/theme-default/src/layout/DocLayout/docComponents/prism-theme.ts
  packages/theme-default/src/styles/base.css
  packages/theme-default/src/styles/code.css
Labels: change: fix

#2174 perf: remove React 17 compatibility code
  packages/core/src/node/initRsbuild.ts
  packages/core/src/node/utils/detectReactVersion.ts
  packages/core/src/runtime/csrClientEntry.tsx
  packages/core/src/runtime/ssrClientEntry.tsx
  packages/runtime/src/Content.tsx
Labels: change: perf

#2177 feat(plugin-shiki): upgrade to shiki@^3.4.2 to support langAlias option
  e2e/fixtures/plugin-shiki/doc/langAlias.mdx
  e2e/fixtures/plugin-shiki/rspress.config.ts
  e2e/tests/plugin-shiki.test.ts
  packages/plugin-shiki/package.json
  packages/shared/package.json
  packages/theme-default/src/styles/base.css
  pnpm-lock.yaml
Labels: change: feat

#2179 docs: update Rstack introduction
  README.md
  packages/document/package.json
  pnpm-lock.yaml
  scripts/dictionary.txt
Labels: change: docs

#2183 docs(plugin-shiki): update package.json description
  packages/plugin-shiki/package.json
  packages/plugin-shiki/src/shiki/pluginShiki.ts
Labels: change: docs

#2188 fix(theme-default): export type CodeButtonGroupProps
  packages/theme-default/src/index.ts
  packages/theme-default/src/layout/DocLayout/docComponents/pre.tsx
Labels: change: fix

#2192 docs: incorrect usage of `socialLinks`
  packages/document/docs/en/guide/default-theme/navbar.mdx
  packages/document/docs/zh/guide/default-theme/navbar.mdx
Labels: change: docs

#2194 fix(plugin-llms): support usage in `ssg: false`
  e2e/fixtures/plugin-llms/doc/_meta.json
  e2e/fixtures/plugin-llms/doc/api/_meta.json
  e2e/fixtures/plugin-llms/doc/api/client-api/_meta.json
  e2e/fixtures/plugin-llms/doc/api/client-api/api-components.mdx
  e2e/fixtures/plugin-llms/doc/api/client-api/api-runtime.mdx
  e2e/fixtures/plugin-llms/doc/api/client-api/index.mdx
  e2e/fixtures/plugin-llms/doc/api/commands.mdx
  e2e/fixtures/plugin-llms/doc/api/config.mdx
  e2e/fixtures/plugin-llms/doc/api/config/_meta.json
  e2e/fixtures/plugin-llms/doc/api/config/config-basic.mdx
  e2e/fixtures/plugin-llms/doc/api/config/config-build.mdx
  e2e/fixtures/plugin-llms/doc/api/config/config-extname.json.mdx
  e2e/fixtures/plugin-llms/doc/api/config/config-frontmatter.mdx
  e2e/fixtures/plugin-llms/doc/api/config/config-theme.mdx
  e2e/fixtures/plugin-llms/doc/api/config/nested.mdx
  e2e/fixtures/plugin-llms/doc/api/config/nested/config-nested.mdx
  e2e/fixtures/plugin-llms/doc/api/index.mdx
  e2e/fixtures/plugin-llms/doc/api/link/_meta.json
  e2e/fixtures/plugin-llms/doc/api/single-page.mdx
  e2e/fixtures/plugin-llms/doc/guide/_meta.json
  e2e/fixtures/plugin-llms/doc/guide/advanced/plugin.mdx
  e2e/fixtures/plugin-llms/doc/guide/index.mdx
  e2e/fixtures/plugin-llms/doc/index.md
  e2e/fixtures/plugin-llms/package.json
  e2e/fixtures/plugin-llms/rspress.config.ts
  e2e/fixtures/plugin-llms/tsconfig.json
  e2e/tests/plugin-llms.test.ts
  packages/plugin-llms/src/plugin.ts
  packages/plugin-llms/src/types.ts
  pnpm-lock.yaml
Labels: change: fix

#2190 feat: add new `CodeBlockRuntime` component
  e2e/fixtures/code-block-runtime/docs/index.mdx
  e2e/fixtures/code-block-runtime/package.json
  e2e/fixtures/code-block-runtime/rspress.config.ts
  e2e/fixtures/code-block-runtime/tsconfig.json
  e2e/tests/code-block-runtime.test.ts
  packages/document/docs/en/fragments/builtin-components.mdx
  packages/document/docs/zh/fragments/builtin-components.mdx
  packages/theme-default/package.json
  packages/theme-default/src/components/CodeBlockRuntime/index.tsx
  packages/theme-default/src/index.ts
  packages/theme-default/src/layout/DocLayout/docComponents/code/CodeButtonGroup.tsx
  packages/theme-default/src/layout/DocLayout/docComponents/pre.tsx
  pnpm-lock.yaml
Labels: change: feat

#2198 docs: incorrect usage of `socialLinks` (#2192)
  packages/document/docs/en/guide/default-theme/navbar.mdx
  packages/document/docs/zh/guide/default-theme/navbar.mdx
Labels: change: docs

#2189 fix: sidebar type=file with data-context
  .changeset/open-zebras-report.md
  e2e/fixtures/auto-nav-sidebar/doc/api/_meta.json
  e2e/tests/auto-nav-sidebar-dir-convension.test.ts
  e2e/tests/auto-nav-sidebar.test.ts
  e2e/tests/i18n.test.ts
  e2e/utils/getSideBar.ts
  packages/theme-default/src/components/Sidebar/SidebarGroup.tsx
  packages/theme-default/src/components/Sidebar/SidebarItem.tsx
  packages/theme-default/src/components/Sidebar/index.tsx
Labels: change: fix

#2195 fix(plugin-shiki/style): for force wrap style
  packages/plugin-shiki/src/shiki.scss
Labels: change: fix

#2209 feat(plugin-shiki): add @rspress/plugin-shiki/transformers exports and transformerCompatibleMetaHighlight
  packages/plugin-shiki/package.json
  packages/plugin-shiki/rslib.config.ts
  packages/plugin-shiki/src/index.ts
  packages/plugin-shiki/src/shiki/pluginShiki.ts
  packages/plugin-shiki/src/shiki/transformers/index.ts
  packages/plugin-shiki/src/transformers/add-title.ts
  packages/plugin-shiki/src/transformers/index.ts
  packages/plugin-shiki/src/transformers/line-number.ts
  packages/plugin-shiki/src/transformers/meta-highlight.ts
  packages/theme-default/src/components/CodeBlockRuntime/index.tsx
Labels: change: feat

#2211 feat(CodeBlockRuntime): add onRendered prop
  packages/theme-default/src/components/CodeBlockRuntime/index.tsx
Labels: change: feat

#2212 fix: exclude `.rspress-toc-exclude` ancestor nodes in dynamic TOC
  packages/theme-default/src/components/Aside/useDynamicToc.ts
Labels: change: fix

#2218 docs: switch to new domain
  README.md
  e2e/fixtures/auto-nav-sidebar/doc/api/_meta.json
  e2e/fixtures/auto-nav-sidebar/doc/api/link/_meta.json
  e2e/fixtures/github-alert-mdxjs/doc/index.mdx
  e2e/fixtures/inline-markdown/doc/index.mdx
  e2e/fixtures/plugin-llms/doc/api/_meta.json
  e2e/fixtures/plugin-llms/doc/api/link/_meta.json
  e2e/tests/inline-markdown.test.ts
  packages/cli/README.md
  packages/core/README.md
  packages/create-rspress/README.md
  packages/create-rspress/package.json
  packages/create-rspress/template-basic/docs/_meta.json
  packages/document/README.md
  packages/document/docs/en/_meta.json
  packages/document/docs/en/api/config/config-build.mdx
  packages/document/docs/en/fragments/builtin-components.mdx
  packages/document/docs/en/guide/advanced/extend-build.mdx
  packages/document/docs/en/guide/basic/ssg.mdx
  packages/document/docs/en/guide/start/introduction.mdx
  packages/document/docs/en/plugin/official-plugins/algolia.mdx
  packages/document/docs/en/plugin/system/introduction.mdx
  packages/document/docs/en/plugin/system/plugin-api.mdx
  packages/document/docs/public/netlify.toml
  packages/document/docs/zh/_meta.json
  packages/document/docs/zh/api/config/config-build.mdx
  packages/document/docs/zh/fragments/builtin-components.mdx
  packages/document/docs/zh/guide/advanced/extend-build.mdx
  packages/document/docs/zh/guide/basic/ssg.mdx
  packages/document/docs/zh/guide/start/introduction.mdx
  packages/document/docs/zh/plugin/official-plugins/algolia.mdx
  packages/document/docs/zh/plugin/system/introduction.mdx
  packages/document/docs/zh/plugin/system/plugin-api.mdx
  packages/document/package.json
  packages/document/rspress.config.ts
  packages/plugin-api-docgen/README.md
  packages/plugin-auto-nav-sidebar/README.md
  packages/plugin-client-redirects/README.md
  packages/plugin-container-syntax/README.md
  packages/plugin-last-updated/README.md
  packages/plugin-llms/README.md
  packages/plugin-medium-zoom/README.md
  packages/plugin-playground/README.md
  packages/plugin-playground/src/web/editor.tsx
  packages/plugin-preview/README.md
  packages/plugin-rss/README.md
  packages/plugin-shiki/README.md
  packages/plugin-typedoc/README.md
  packages/shared/src/node-utils/getIconUrlPath.ts
  packages/shared/src/runtime-utils/utils.ts
  pnpm-lock.yaml
Labels: change: docs

#2221 fix: empty blockquote crash the compiler
  .changeset/better-eels-tap.md
  packages/plugin-container-syntax/src/remarkPlugin.ts
  packages/plugin-container-syntax/tests/__snapshots__/index.test.ts.snap
  packages/plugin-container-syntax/tests/index.test.ts
Labels: change: fix

#2226 docs: upgrade the algolia template
  packages/document/docs/en/plugin/official-plugins/algolia.mdx
  packages/document/docs/zh/plugin/official-plugins/algolia.mdx
Labels: change: docs

#2228 fix(infra): bundle size regression after migrating to bundleless dist
  packages/theme-default/index-barrel.js
  packages/theme-default/rslib.config.ts
  packages/theme-default/src/index.ts
Labels: change: fix
